In [1]:
import warnings
import numpy as np
import pandas as pd
import pyarrow
import fastparquet
import altair as alt
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier

warnings.filterwarnings("ignore")
%matplotlib inline
pd.options.display.precision = 15
alt.renderers.enable('mimetype')
%env JOBLIB_TEMP_FOLDER=/tmp

env: JOBLIB_TEMP_FOLDER=/tmp

In [2]:
# folder_path = 'dataset/'
from pathlib import Path
import pandas as pd

# Detect environment
try:
    import google.colab

    IS_COLAB = True
    from google.colab import drive
    drive.mount("/content/drive")
except ImportError:
    IS_COLAB = False

# Root paths
if IS_COLAB:
    ROOT = Path("/content/drive/MyDrive/minor-thesis")
else:
    ROOT = Path.cwd()

DATASET_PATH = ROOT / "dataset"
SAVED_PATH = ROOT / "saved"

print(f"Running on {'Google Colab' if IS_COLAB else 'Local'}")
print(f"Dataset path: {DATASET_PATH}")

Running on Local
Dataset path: d:\source\RMIT\master-of-ai-new\2026-semester-02\minor-thesis\dataset

In [3]:
train = pd.read_parquet(f"{DATASET_PATH}/merged_train.parquet")
test = pd.read_parquet(f"{DATASET_PATH}/merged_test.parquet")

RANDOM_SEED = 42
START_DATE = "2026-01-01"

In [4]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    confusion_matrix,
    balanced_accuracy_score,
    matthews_corrcoef,
    classification_report,
)


def run_random_forest(X_train, X_valid, y_train, y_valid, name="Random Forest"):
    print(f"\n{'=' * 60}")
    print(name)
    print(f"{'=' * 60}")
    print(f"Features: {X_train.shape[1]}")

    model = RandomForestClassifier(
        n_estimators=300, class_weight="balanced", random_state=RANDOM_SEED, n_jobs=-1
    )

    model.fit(X_train, y_train)

    y_pred = model.predict(X_valid)
    y_pred_prob = model.predict_proba(X_valid)[:, 1]

    accuracy = accuracy_score(y_valid, y_pred)
    precision = precision_score(y_valid, y_pred, zero_division=0)
    recall = recall_score(y_valid, y_pred, zero_division=0)
    f1 = f1_score(y_valid, y_pred, zero_division=0)
    roc_auc = roc_auc_score(y_valid, y_pred_prob)
    pr_auc = average_precision_score(y_valid, y_pred_prob)
    balanced_acc = balanced_accuracy_score(y_valid, y_pred)
    mcc = matthews_corrcoef(y_valid, y_pred)
    cm = confusion_matrix(y_valid, y_pred)

    print(f"Accuracy           : {accuracy:.4f}")
    print(f"Precision          : {precision:.4f}")
    print(f"Recall             : {recall:.4f}")
    print(f"F1 Score           : {f1:.4f}")
    print(f"ROC-AUC            : {roc_auc:.4f}")
    print(f"PR-AUC             : {pr_auc:.4f}")
    print(f"Balanced Accuracy  : {balanced_acc:.4f}")
    print(f"MCC                : {mcc:.4f}")

    print("\nConfusion Matrix:")
    print(cm)

    print("\nClassification Report:")
    print(
        classification_report(
            y_valid,
            y_pred,
            target_names=["Legitimate", "Fraud"],
            digits=4,
            zero_division=0,
        )
    )

    import gc

    gc.collect()
    del model

    return {
        "Model": name,
        "Features": X_train.shape[1],
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1": f1,
        "ROC-AUC": roc_auc,
        "PR-AUC": pr_auc,
        "Balanced Accuracy": balanced_acc,
        "MCC": mcc,
        "Confusion Matrix": cm,
    }

In [5]:
# LightGBM
from lightgbm import LGBMClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    confusion_matrix,
    balanced_accuracy_score,
    matthews_corrcoef,
    classification_report,
)


def run_lightgbm(X_train, X_valid, y_train, y_valid, name="LightGBM"):
    print(f"\n{'=' * 60}")
    print(name)
    print(f"{'=' * 60}")
    print(f"Features: {X_train.shape[1]}")

    model = LGBMClassifier(
        n_estimators=500,
        learning_rate=0.05,
        max_depth=-1,
        num_leaves=31,
        class_weight="balanced",
        random_state=RANDOM_SEED,
        n_jobs=-1,
        verbosity=-1,
    )

    model.fit(X_train, y_train)

    y_pred = model.predict(X_valid)
    y_pred_prob = model.predict_proba(X_valid)[:, 1]

    accuracy = accuracy_score(y_valid, y_pred)
    precision = precision_score(y_valid, y_pred, zero_division=0)
    recall = recall_score(y_valid, y_pred, zero_division=0)
    f1 = f1_score(y_valid, y_pred, zero_division=0)
    roc_auc = roc_auc_score(y_valid, y_pred_prob)
    pr_auc = average_precision_score(y_valid, y_pred_prob)
    balanced_acc = balanced_accuracy_score(y_valid, y_pred)
    mcc = matthews_corrcoef(y_valid, y_pred)
    cm = confusion_matrix(y_valid, y_pred)

    print(f"Accuracy           : {accuracy:.4f}")
    print(f"Precision          : {precision:.4f}")
    print(f"Recall             : {recall:.4f}")
    print(f"F1 Score           : {f1:.4f}")
    print(f"ROC-AUC            : {roc_auc:.4f}")
    print(f"PR-AUC             : {pr_auc:.4f}")
    print(f"Balanced Accuracy  : {balanced_acc:.4f}")
    print(f"MCC                : {mcc:.4f}")

    print("\nConfusion Matrix:")
    print(cm)

    print("\nClassification Report:")
    print(
        classification_report(
            y_valid,
            y_pred,
            target_names=["Legitimate", "Fraud"],
            digits=4,
            zero_division=0,
        )
    )

    import gc

    gc.collect()
    del model

    return {
        "Model": name,
        "Features": X_train.shape[1],
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1": f1,
        "ROC-AUC": roc_auc,
        "PR-AUC": pr_auc,
        "Balanced Accuracy": balanced_acc,
        "MCC": mcc,
        "Confusion Matrix": cm,
    }

In [6]:
# XGBoost
from xgboost import XGBClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    confusion_matrix,
    balanced_accuracy_score,
    matthews_corrcoef,
    classification_report,
)


def run_xgboost(X_train, X_valid, y_train, y_valid, name="XGBoost"):
    print(f"\n{'=' * 60}")
    print(name)
    print(f"{'=' * 60}")
    print(f"Features: {X_train.shape[1]}")

    model = XGBClassifier(
        n_estimators=500,
        learning_rate=0.05,
        max_depth=6,
        random_state=RANDOM_SEED,
        n_jobs=-1,
        eval_metric="logloss",
        scale_pos_weight=(y_train == 0).sum() / (y_train == 1).sum(),
    )

    model.fit(X_train, y_train)

    y_pred = model.predict(X_valid)
    y_pred_prob = model.predict_proba(X_valid)[:, 1]

    accuracy = accuracy_score(y_valid, y_pred)
    precision = precision_score(y_valid, y_pred, zero_division=0)
    recall = recall_score(y_valid, y_pred, zero_division=0)
    f1 = f1_score(y_valid, y_pred, zero_division=0)
    roc_auc = roc_auc_score(y_valid, y_pred_prob)
    pr_auc = average_precision_score(y_valid, y_pred_prob)
    balanced_acc = balanced_accuracy_score(y_valid, y_pred)
    mcc = matthews_corrcoef(y_valid, y_pred)
    cm = confusion_matrix(y_valid, y_pred)

    print(f"Accuracy           : {accuracy:.4f}")
    print(f"Precision          : {precision:.4f}")
    print(f"Recall             : {recall:.4f}")
    print(f"F1 Score           : {f1:.4f}")
    print(f"ROC-AUC            : {roc_auc:.4f}")
    print(f"PR-AUC             : {pr_auc:.4f}")
    print(f"Balanced Accuracy  : {balanced_acc:.4f}")
    print(f"MCC                : {mcc:.4f}")

    print("\nConfusion Matrix:")
    print(cm)

    print("\nClassification Report:")
    print(
        classification_report(
            y_valid,
            y_pred,
            target_names=["Legitimate", "Fraud"],
            digits=4,
            zero_division=0,
        )
    )

    import gc

    gc.collect()
    del model

    return {
        "Model": name,
        "Features": X_train.shape[1],
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1": f1,
        "ROC-AUC": roc_auc,
        "PR-AUC": pr_auc,
        "Balanced Accuracy": balanced_acc,
        "MCC": mcc,
        "Confusion Matrix": cm,
    }

In [7]:
# DATA SPLIT / EXPERIMENT DATASETS
from itertools import combinations

train = train.sort_values("TransactionDT").reset_index(drop=True)

y = train["isFraud"]

split_idx = int(len(train) * 0.8)

y_train = y.iloc[:split_idx]
y_valid = y.iloc[split_idx:]


# Baseline
# Original features, excluding engineered UID / UID2

baseline_cols = [
    col
    for col in train.columns
    if col not in ["isFraud", "TransactionID", "uid", "uid2"]
]

X_baseline = train[baseline_cols]

X_train_baseline = X_baseline.iloc[:split_idx]
X_valid_baseline = X_baseline.iloc[split_idx:]


# Feature Engineering
# Original + temporal + UID + UID2

feature_cols = [col for col in train.columns if col not in ["isFraud", "TransactionID"]]

X_features = train[feature_cols]

X_train_features = X_features.iloc[:split_idx]
X_valid_features = X_features.iloc[split_idx:]


# Feature-group ablation

prefix_groups = {
    "C": ("C",),
    "D": ("D",),
    "M": ("M",),
    "id": ("id_",),
    "V": ("V",),
}

group_names = list(prefix_groups.keys())

ablation_datasets = {}

for r in range(1, len(group_names) + 1):

    for combination in combinations(group_names, r):

        prefixes = tuple(
            prefix for group in combination for prefix in prefix_groups[group]
        )

        selected_cols = [col for col in baseline_cols if not col.startswith(prefixes)]

        X = train[selected_cols]

        name = "Remove " + " + ".join(combination)

        ablation_datasets[name] = (X.iloc[:split_idx], X.iloc[split_idx:])

print("Baseline features :", len(baseline_cols))
print("Feature engineering:", len(feature_cols))
print("Ablation experiments:", len(ablation_datasets))

Baseline features : 437
Feature engineering: 439
Ablation experiments: 31

In [8]:
# ALL ML EXPERIMENTS
rf_results = []
lgb_results = []
xgb_results = []

In [9]:
def save_results():

    def prepare(results):
        df = pd.DataFrame(results).copy()

        # Convert model objects to model names
        if "model" in df.columns:
            df["model"] = df["model"].apply(lambda x: type(x).__name__)

        # Convert confusion matrix to TN/FP/FN/TP
        if "Confusion Matrix" in df.columns:
            cm = df.pop("Confusion Matrix").tolist()

            df["TN"] = [x[0][0] for x in cm]
            df["FP"] = [x[0][1] for x in cm]
            df["FN"] = [x[1][0] for x in cm]
            df["TP"] = [x[1][1] for x in cm]

        return df

    prepare(rf_results).to_parquet(f"{SAVED_PATH}/rf_results.parquet", index=False)

    prepare(lgb_results).to_parquet(f"{SAVED_PATH}/lgb_results.parquet", index=False)

    prepare(xgb_results).to_parquet(f"{SAVED_PATH}/xgb_results.parquet", index=False)

In [10]:
# 1. BASELINE - RF

rf_results.append(
    run_random_forest(
        X_train_baseline, X_valid_baseline, y_train, y_valid, "RF - Baseline"
    )
)
save_results()

# 2. FEATURE ENGINEERING

rf_results.append(
    run_random_forest(
        X_train_features, X_valid_features, y_train, y_valid, "RF - Feature Engineering"
    )
)

save_results()

============================================================
RF - Baseline
============================================================
Features: 437
Accuracy           : 0.9740
Precision          : 0.8058
Recall             : 0.3206
F1 Score           : 0.4587
ROC-AUC            : 0.9056
PR-AUC             : 0.5279
Balanced Accuracy  : 0.6589
MCC                : 0.4986

Confusion Matrix:
[[113730    314]
 [  2761   1303]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9763    0.9972    0.9867    114044
       Fraud     0.8058    0.3206    0.4587      4064

    accuracy                         0.9740    118108
   macro avg     0.8911    0.6589    0.7227    118108
weighted avg     0.9704    0.9740    0.9685    118108


============================================================
RF - Feature Engineering
============================================================
Features: 439
Accuracy           : 0.9742
Precision          : 0.8149
Recall             : 0.3238
F1 Score           : 0.4635
ROC-AUC            : 0.9074
PR-AUC             : 0.5341
Balanced Accuracy  : 0.6606
MCC                : 0.5041

Confusion Matrix:
[[113745    299]
 [  2748   1316]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9764    0.9974    0.9868    114044
       Fraud     0.8149    0.3238    0.4635      4064

    accuracy                         0.9742    118108
   macro avg     0.8956    0.6606    0.7251    118108
weighted avg     0.9709    0.9742    0.9688    118108

In [11]:
# 1. BASELINE - LGBM
lgb_results.append(
    run_lightgbm(
        X_train_baseline, X_valid_baseline, y_train, y_valid, "LightGBM - Baseline"
    )
)
save_results()

# 2. FEATURE ENGINEERING
lgb_results.append(
    run_lightgbm(
        X_train_features,
        X_valid_features,
        y_train,
        y_valid,
        "LightGBM - Feature Engineering",
    )
)
save_results()

============================================================
LightGBM - Baseline
============================================================
Features: 437
Accuracy           : 0.9008
Precision          : 0.2180
Recall             : 0.7274
F1 Score           : 0.3355
ROC-AUC            : 0.9057
PR-AUC             : 0.5203
Balanced Accuracy  : 0.8172
MCC                : 0.3627

Confusion Matrix:
[[103440  10604]
 [  1108   2956]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9894    0.9070    0.9464    114044
       Fraud     0.2180    0.7274    0.3355      4064

    accuracy                         0.9008    118108
   macro avg     0.6037    0.8172    0.6409    118108
weighted avg     0.9629    0.9008    0.9254    118108


============================================================
LightGBM - Feature Engineering
============================================================
Features: 439
Accuracy           : 0.9017
Precision          : 0.2191
Recall             : 0.7247
F1 Score           : 0.3365
ROC-AUC            : 0.9050
PR-AUC             : 0.5175
Balanced Accuracy  : 0.8163
MCC                : 0.3631

Confusion Matrix:
[[103550  10494]
 [  1119   2945]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9893    0.9080    0.9469    114044
       Fraud     0.2191    0.7247    0.3365      4064

    accuracy                         0.9017    118108
   macro avg     0.6042    0.8163    0.6417    118108
weighted avg     0.9628    0.9017    0.9259    118108

In [12]:
# 1. BASELINE - XGB
xgb_results.append(
    run_xgboost(
        X_train_baseline, X_valid_baseline, y_train, y_valid, "XGBoost - Baseline"
    )
)
save_results()

# 2. FEATURE ENGINEERING
xgb_results.append(
    run_xgboost(
        X_train_features,
        X_valid_features,
        y_train,
        y_valid,
        "XGBoost - Feature Engineering",
    )
)
save_results()

============================================================
XGBoost - Baseline
============================================================
Features: 437
Accuracy           : 0.9110
Precision          : 0.2365
Recall             : 0.7124
F1 Score           : 0.3551
ROC-AUC            : 0.9017
PR-AUC             : 0.5170
Balanced Accuracy  : 0.8152
MCC                : 0.3770

Confusion Matrix:
[[104698   9346]
 [  1169   2895]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9890    0.9180    0.9522    114044
       Fraud     0.2365    0.7124    0.3551      4064

    accuracy                         0.9110    118108
   macro avg     0.6127    0.8152    0.6536    118108
weighted avg     0.9631    0.9110    0.9316    118108


============================================================
XGBoost - Feature Engineering
============================================================
Features: 439
Accuracy           : 0.9126
Precision          : 0.2395
Recall             : 0.7084
F1 Score           : 0.3580
ROC-AUC            : 0.9027
PR-AUC             : 0.5217
Balanced Accuracy  : 0.8141
MCC                : 0.3788

Confusion Matrix:
[[104904   9140]
 [  1185   2879]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9888    0.9199    0.9531    114044
       Fraud     0.2395    0.7084    0.3580      4064

    accuracy                         0.9126    118108
   macro avg     0.6142    0.8141    0.6556    118108
weighted avg     0.9630    0.9126    0.9326    118108

In [13]:
# 3. ALL ABLATION EXPERIMENTS
for name, (X_train, X_valid) in ablation_datasets.items():

    rf_results.append(
        run_random_forest(X_train, X_valid, y_train, y_valid, f"RF - {name}")
    )
    save_results()

============================================================
RF - Remove C
============================================================
Features: 423
Accuracy           : 0.9729
Precision          : 0.7940
Recall             : 0.2864
F1 Score           : 0.4210
ROC-AUC            : 0.8916
PR-AUC             : 0.4879
Balanced Accuracy  : 0.6419
MCC                : 0.4672

Confusion Matrix:
[[113742    302]
 [  2900   1164]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9751    0.9974    0.9861    114044
       Fraud     0.7940    0.2864    0.4210      4064

    accuracy                         0.9729    118108
   macro avg     0.8846    0.6419    0.7035    118108
weighted avg     0.9689    0.9729    0.9667    118108


============================================================
RF - Remove D
============================================================
Features: 415
Accuracy           : 0.9744
Precision          : 0.8049
Recall             : 0.3381
F1 Score           : 0.4762
ROC-AUC            : 0.9046
PR-AUC             : 0.5272
Balanced Accuracy  : 0.6676
MCC                : 0.5119

Confusion Matrix:
[[113711    333]
 [  2690   1374]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9769    0.9971    0.9869    114044
       Fraud     0.8049    0.3381    0.4762      4064

    accuracy                         0.9744    118108
   macro avg     0.8909    0.6676    0.7315    118108
weighted avg     0.9710    0.9744    0.9693    118108


============================================================
RF - Remove M
============================================================
Features: 428
Accuracy           : 0.9740
Precision          : 0.8075
Recall             : 0.3221
F1 Score           : 0.4605
ROC-AUC            : 0.9018
PR-AUC             : 0.5233
Balanced Accuracy  : 0.6597
MCC                : 0.5003

Confusion Matrix:
[[113732    312]
 [  2755   1309]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9763    0.9973    0.9867    114044
       Fraud     0.8075    0.3221    0.4605      4064

    accuracy                         0.9740    118108
   macro avg     0.8919    0.6597    0.7236    118108
weighted avg     0.9705    0.9740    0.9686    118108


============================================================
RF - Remove id
============================================================
Features: 399
Accuracy           : 0.9741
Precision          : 0.8061
Recall             : 0.3263
F1 Score           : 0.4645
ROC-AUC            : 0.9031
PR-AUC             : 0.5275
Balanced Accuracy  : 0.6617
MCC                : 0.5031

Confusion Matrix:
[[113725    319]
 [  2738   1326]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9765    0.9972    0.9867    114044
       Fraud     0.8061    0.3263    0.4645      4064

    accuracy                         0.9741    118108
   macro avg     0.8913    0.6617    0.7256    118108
weighted avg     0.9706    0.9741    0.9688    118108


============================================================
RF - Remove V
============================================================
Features: 98
Accuracy           : 0.9733
Precision          : 0.8276
Recall             : 0.2835
F1 Score           : 0.4223
ROC-AUC            : 0.9133
PR-AUC             : 0.5445
Balanced Accuracy  : 0.6407
MCC                : 0.4752

Confusion Matrix:
[[113804    240]
 [  2912   1152]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9751    0.9979    0.9863    114044
       Fraud     0.8276    0.2835    0.4223      4064

    accuracy                         0.9733    118108
   macro avg     0.9013    0.6407    0.7043    118108
weighted avg     0.9700    0.9733    0.9669    118108


============================================================
RF - Remove C + D
============================================================
Features: 401
Accuracy           : 0.9731
Precision          : 0.7834
Recall             : 0.3000
F1 Score           : 0.4338
ROC-AUC            : 0.8894
PR-AUC             : 0.4861
Balanced Accuracy  : 0.6485
MCC                : 0.4748

Confusion Matrix:
[[113707    337]
 [  2845   1219]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9756    0.9970    0.9862    114044
       Fraud     0.7834    0.3000    0.4338      4064

    accuracy                         0.9731    118108
   macro avg     0.8795    0.6485    0.7100    118108
weighted avg     0.9690    0.9731    0.9672    118108


============================================================
RF - Remove C + M
============================================================
Features: 414
Accuracy           : 0.9728
Precision          : 0.7923
Recall             : 0.2825
F1 Score           : 0.4165
ROC-AUC            : 0.8879
PR-AUC             : 0.4799
Balanced Accuracy  : 0.6399
MCC                : 0.4634

Confusion Matrix:
[[113743    301]
 [  2916   1148]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9750    0.9974    0.9861    114044
       Fraud     0.7923    0.2825    0.4165      4064

    accuracy                         0.9728    118108
   macro avg     0.8836    0.6399    0.7013    118108
weighted avg     0.9687    0.9728    0.9665    118108


============================================================
RF - Remove C + id
============================================================
Features: 385
Accuracy           : 0.9729
Precision          : 0.7895
Recall             : 0.2889
F1 Score           : 0.4230
ROC-AUC            : 0.8890
PR-AUC             : 0.4825
Balanced Accuracy  : 0.6431
MCC                : 0.4678

Confusion Matrix:
[[113731    313]
 [  2890   1174]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9752    0.9973    0.9861    114044
       Fraud     0.7895    0.2889    0.4230      4064

    accuracy                         0.9729    118108
   macro avg     0.8824    0.6431    0.7046    118108
weighted avg     0.9688    0.9729    0.9667    118108


============================================================
RF - Remove C + V
============================================================
Features: 84
Accuracy           : 0.9685
Precision          : 0.7515
Recall             : 0.1257
F1 Score           : 0.2154
ROC-AUC            : 0.8894
PR-AUC             : 0.4076
Balanced Accuracy  : 0.5621
MCC                : 0.2994

Confusion Matrix:
[[113875    169]
 [  3553    511]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9697    0.9985    0.9839    114044
       Fraud     0.7515    0.1257    0.2154      4064

    accuracy                         0.9685    118108
   macro avg     0.8606    0.5621    0.5997    118108
weighted avg     0.9622    0.9685    0.9575    118108


============================================================
RF - Remove D + M
============================================================
Features: 406
Accuracy           : 0.9742
Precision          : 0.7935
Recall             : 0.3386
F1 Score           : 0.4746
ROC-AUC            : 0.8962
PR-AUC             : 0.5137
Balanced Accuracy  : 0.6677
MCC                : 0.5084

Confusion Matrix:
[[113686    358]
 [  2688   1376]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9769    0.9969    0.9868    114044
       Fraud     0.7935    0.3386    0.4746      4064

    accuracy                         0.9742    118108
   macro avg     0.8852    0.6677    0.7307    118108
weighted avg     0.9706    0.9742    0.9692    118108


============================================================
RF - Remove D + id
============================================================
Features: 377
Accuracy           : 0.9739
Precision          : 0.7712
Recall             : 0.3450
F1 Score           : 0.4767
ROC-AUC            : 0.8980
PR-AUC             : 0.5158
Balanced Accuracy  : 0.6707
MCC                : 0.5054

Confusion Matrix:
[[113628    416]
 [  2662   1402]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9771    0.9964    0.9866    114044
       Fraud     0.7712    0.3450    0.4767      4064

    accuracy                         0.9739    118108
   macro avg     0.8741    0.6707    0.7317    118108
weighted avg     0.9700    0.9739    0.9691    118108


============================================================
RF - Remove D + V
============================================================
Features: 76
Accuracy           : 0.9754
Precision          : 0.8478
Recall             : 0.3482
F1 Score           : 0.4936
ROC-AUC            : 0.9091
PR-AUC             : 0.5696
Balanced Accuracy  : 0.6730
MCC                : 0.5343

Confusion Matrix:
[[113790    254]
 [  2649   1415]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9772    0.9978    0.9874    114044
       Fraud     0.8478    0.3482    0.4936      4064

    accuracy                         0.9754    118108
   macro avg     0.9125    0.6730    0.7405    118108
weighted avg     0.9728    0.9754    0.9704    118108


============================================================
RF - Remove M + id
============================================================
Features: 390
Accuracy           : 0.9740
Precision          : 0.8027
Recall             : 0.3243
F1 Score           : 0.4620
ROC-AUC            : 0.8980
PR-AUC             : 0.5172
Balanced Accuracy  : 0.6607
MCC                : 0.5005

Confusion Matrix:
[[113720    324]
 [  2746   1318]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9764    0.9972    0.9867    114044
       Fraud     0.8027    0.3243    0.4620      4064

    accuracy                         0.9740    118108
   macro avg     0.8896    0.6607    0.7243    118108
weighted avg     0.9704    0.9740    0.9686    118108


============================================================
RF - Remove M + V
============================================================
Features: 89
Accuracy           : 0.9731
Precision          : 0.8212
Recall             : 0.2803
F1 Score           : 0.4179
ROC-AUC            : 0.9055
PR-AUC             : 0.5288
Balanced Accuracy  : 0.6390
MCC                : 0.4705

Confusion Matrix:
[[113796    248]
 [  2925   1139]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9749    0.9978    0.9863    114044
       Fraud     0.8212    0.2803    0.4179      4064

    accuracy                         0.9731    118108
   macro avg     0.8981    0.6390    0.7021    118108
weighted avg     0.9697    0.9731    0.9667    118108


============================================================
RF - Remove id + V
============================================================
Features: 60
Accuracy           : 0.9736
Precision          : 0.8333
Recall             : 0.2904
F1 Score           : 0.4307
ROC-AUC            : 0.9114
PR-AUC             : 0.5450
Balanced Accuracy  : 0.6441
MCC                : 0.4828

Confusion Matrix:
[[113808    236]
 [  2884   1180]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9753    0.9979    0.9865    114044
       Fraud     0.8333    0.2904    0.4307      4064

    accuracy                         0.9736    118108
   macro avg     0.9043    0.6441    0.7086    118108
weighted avg     0.9704    0.9736    0.9674    118108


============================================================
RF - Remove C + D + M
============================================================
Features: 392
Accuracy           : 0.9728
Precision          : 0.7715
Recall             : 0.2982
F1 Score           : 0.4302
ROC-AUC            : 0.8818
PR-AUC             : 0.4723
Balanced Accuracy  : 0.6475
MCC                : 0.4695

Confusion Matrix:
[[113685    359]
 [  2852   1212]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9755    0.9969    0.9861    114044
       Fraud     0.7715    0.2982    0.4302      4064

    accuracy                         0.9728    118108
   macro avg     0.8735    0.6475    0.7081    118108
weighted avg     0.9685    0.9728    0.9669    118108


============================================================
RF - Remove C + D + id
============================================================
Features: 363
Accuracy           : 0.9725
Precision          : 0.7419
Recall             : 0.3083
F1 Score           : 0.4356
ROC-AUC            : 0.8803
PR-AUC             : 0.4694
Balanced Accuracy  : 0.6522
MCC                : 0.4675

Confusion Matrix:
[[113608    436]
 [  2811   1253]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9759    0.9962    0.9859    114044
       Fraud     0.7419    0.3083    0.4356      4064

    accuracy                         0.9725    118108
   macro avg     0.8589    0.6522    0.7108    118108
weighted avg     0.9678    0.9725    0.9670    118108


============================================================
RF - Remove C + D + V
============================================================
Features: 62
Accuracy           : 0.9696
Precision          : 0.7748
Recall             : 0.1634
F1 Score           : 0.2699
ROC-AUC            : 0.8654
PR-AUC             : 0.3935
Balanced Accuracy  : 0.5808
MCC                : 0.3473

Confusion Matrix:
[[113851    193]
 [  3400    664]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9710    0.9983    0.9845    114044
       Fraud     0.7748    0.1634    0.2699      4064

    accuracy                         0.9696    118108
   macro avg     0.8729    0.5808    0.6272    118108
weighted avg     0.9643    0.9696    0.9599    118108


============================================================
RF - Remove C + M + id
============================================================
Features: 376
Accuracy           : 0.9727
Precision          : 0.7791
Recall             : 0.2864
F1 Score           : 0.4189
ROC-AUC            : 0.8842
PR-AUC             : 0.4763
Balanced Accuracy  : 0.6418
MCC                : 0.4624

Confusion Matrix:
[[113714    330]
 [  2900   1164]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9751    0.9971    0.9860    114044
       Fraud     0.7791    0.2864    0.4189      4064

    accuracy                         0.9727    118108
   macro avg     0.8771    0.6418    0.7024    118108
weighted avg     0.9684    0.9727    0.9665    118108


============================================================
RF - Remove C + M + V
============================================================
Features: 75
Accuracy           : 0.9681
Precision          : 0.7363
Recall             : 0.1154
F1 Score           : 0.1995
ROC-AUC            : 0.8730
PR-AUC             : 0.3781
Balanced Accuracy  : 0.5570
MCC                : 0.2835

Confusion Matrix:
[[113876    168]
 [  3595    469]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9694    0.9985    0.9837    114044
       Fraud     0.7363    0.1154    0.1995      4064

    accuracy                         0.9681    118108
   macro avg     0.8528    0.5570    0.5916    118108
weighted avg     0.9614    0.9681    0.9568    118108


============================================================
RF - Remove C + id + V
============================================================
Features: 46
Accuracy           : 0.9680
Precision          : 0.7300
Recall             : 0.1125
F1 Score           : 0.1949
ROC-AUC            : 0.8808
PR-AUC             : 0.3767
Balanced Accuracy  : 0.5555
MCC                : 0.2786

Confusion Matrix:
[[113875    169]
 [  3607    457]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9693    0.9985    0.9837    114044
       Fraud     0.7300    0.1125    0.1949      4064

    accuracy                         0.9680    118108
   macro avg     0.8497    0.5555    0.5893    118108
weighted avg     0.9611    0.9680    0.9565    118108


============================================================
RF - Remove D + M + id
============================================================
Features: 368
Accuracy           : 0.9737
Precision          : 0.7605
Recall             : 0.3430
F1 Score           : 0.4728
ROC-AUC            : 0.8910
PR-AUC             : 0.5024
Balanced Accuracy  : 0.6696
MCC                : 0.5001

Confusion Matrix:
[[113605    439]
 [  2670   1394]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9770    0.9962    0.9865    114044
       Fraud     0.7605    0.3430    0.4728      4064

    accuracy                         0.9737    118108
   macro avg     0.8688    0.6696    0.7296    118108
weighted avg     0.9696    0.9737    0.9688    118108


============================================================
RF - Remove D + M + V
============================================================
Features: 67
Accuracy           : 0.9750
Precision          : 0.8277
Recall             : 0.3452
F1 Score           : 0.4872
ROC-AUC            : 0.9032
PR-AUC             : 0.5630
Balanced Accuracy  : 0.6713
MCC                : 0.5252

Confusion Matrix:
[[113752    292]
 [  2661   1403]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9771    0.9974    0.9872    114044
       Fraud     0.8277    0.3452    0.4872      4064

    accuracy                         0.9750    118108
   macro avg     0.9024    0.6713    0.7372    118108
weighted avg     0.9720    0.9750    0.9700    118108


============================================================
RF - Remove D + id + V
============================================================
Features: 38
Accuracy           : 0.9750
Precision          : 0.7966
Recall             : 0.3671
F1 Score           : 0.5026
ROC-AUC            : 0.9060
PR-AUC             : 0.5595
Balanced Accuracy  : 0.6819
MCC                : 0.5308

Confusion Matrix:
[[113663    381]
 [  2572   1492]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9779    0.9967    0.9872    114044
       Fraud     0.7966    0.3671    0.5026      4064

    accuracy                         0.9750    118108
   macro avg     0.8872    0.6819    0.7449    118108
weighted avg     0.9716    0.9750    0.9705    118108


============================================================
RF - Remove M + id + V
============================================================
Features: 51
Accuracy           : 0.9733
Precision          : 0.8264
Recall             : 0.2835
F1 Score           : 0.4221
ROC-AUC            : 0.9048
PR-AUC             : 0.5303
Balanced Accuracy  : 0.6407
MCC                : 0.4748

Confusion Matrix:
[[113802    242]
 [  2912   1152]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9751    0.9979    0.9863    114044
       Fraud     0.8264    0.2835    0.4221      4064

    accuracy                         0.9733    118108
   macro avg     0.9007    0.6407    0.7042    118108
weighted avg     0.9699    0.9733    0.9669    118108


============================================================
RF - Remove C + D + M + id
============================================================
Features: 354
Accuracy           : 0.9723
Precision          : 0.7340
Recall             : 0.3068
F1 Score           : 0.4328
ROC-AUC            : 0.8734
PR-AUC             : 0.4567
Balanced Accuracy  : 0.6514

In [14]:
# 3. ALL ABLATION EXPERIMENTS
for name, (X_train, X_valid) in ablation_datasets.items():
    lgb_results.append(
        run_lightgbm(X_train, X_valid, y_train, y_valid, f"LightGBM - {name}")
    )

    save_results()

============================================================
LightGBM - Remove C
============================================================
Features: 423
Accuracy           : 0.8939
Precision          : 0.2027
Recall             : 0.7104
F1 Score           : 0.3155
ROC-AUC            : 0.8941
PR-AUC             : 0.4810
Balanced Accuracy  : 0.8054
MCC                : 0.3419

Confusion Matrix:
[[102691  11353]
 [  1177   2887]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9887    0.9005    0.9425    114044
       Fraud     0.2027    0.7104    0.3155      4064

    accuracy                         0.8939    118108
   macro avg     0.5957    0.8054    0.6290    118108
weighted avg     0.9616    0.8939    0.9209    118108


============================================================
LightGBM - Remove D
============================================================
Features: 415
Accuracy           : 0.8969
Precision          : 0.2108
Recall             : 0.7281
F1 Score           : 0.3270
ROC-AUC            : 0.9021
PR-AUC             : 0.5206
Balanced Accuracy  : 0.8155
MCC                : 0.3554

Confusion Matrix:
[[102968  11076]
 [  1105   2959]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9894    0.9029    0.9442    114044
       Fraud     0.2108    0.7281    0.3270      4064

    accuracy                         0.8969    118108
   macro avg     0.6001    0.8155    0.6356    118108
weighted avg     0.9626    0.8969    0.9229    118108


============================================================
LightGBM - Remove M
============================================================
Features: 428
Accuracy           : 0.8976
Precision          : 0.2102
Recall             : 0.7165
F1 Score           : 0.3251
ROC-AUC            : 0.8992
PR-AUC             : 0.5149
Balanced Accuracy  : 0.8103
MCC                : 0.3516

Confusion Matrix:
[[103103  10941]
 [  1152   2912]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9890    0.9041    0.9446    114044
       Fraud     0.2102    0.7165    0.3251      4064

    accuracy                         0.8976    118108
   macro avg     0.5996    0.8103    0.6348    118108
weighted avg     0.9622    0.8976    0.9233    118108


============================================================
LightGBM - Remove id
============================================================
Features: 399
Accuracy           : 0.8989
Precision          : 0.2152
Recall             : 0.7323
F1 Score           : 0.3326
ROC-AUC            : 0.9082
PR-AUC             : 0.5149
Balanced Accuracy  : 0.8186
MCC                : 0.3612

Confusion Matrix:
[[103191  10853]
 [  1088   2976]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9896    0.9048    0.9453    114044
       Fraud     0.2152    0.7323    0.3326      4064

    accuracy                         0.8989    118108
   macro avg     0.6024    0.8186    0.6390    118108
weighted avg     0.9629    0.8989    0.9242    118108


============================================================
LightGBM - Remove V
============================================================
Features: 98
Accuracy           : 0.8931
Precision          : 0.2079
Recall             : 0.7490
F1 Score           : 0.3254
ROC-AUC            : 0.9098
PR-AUC             : 0.5174
Balanced Accuracy  : 0.8236
MCC                : 0.3580

Confusion Matrix:
[[102443  11601]
 [  1020   3044]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9901    0.8983    0.9420    114044
       Fraud     0.2079    0.7490    0.3254      4064

    accuracy                         0.8931    118108
   macro avg     0.5990    0.8236    0.6337    118108
weighted avg     0.9632    0.8931    0.9208    118108


============================================================
LightGBM - Remove C + D
============================================================
Features: 401
Accuracy           : 0.8924
Precision          : 0.2000
Recall             : 0.7089
F1 Score           : 0.3119
ROC-AUC            : 0.8857
PR-AUC             : 0.4818
Balanced Accuracy  : 0.8039
MCC                : 0.3386

Confusion Matrix:
[[102518  11526]
 [  1183   2881]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9886    0.8989    0.9416    114044
       Fraud     0.2000    0.7089    0.3119      4064

    accuracy                         0.8924    118108
   macro avg     0.5943    0.8039    0.6268    118108
weighted avg     0.9615    0.8924    0.9200    118108


============================================================
LightGBM - Remove C + M
============================================================
Features: 414
Accuracy           : 0.8894
Precision          : 0.1950
Recall             : 0.7074
F1 Score           : 0.3057
ROC-AUC            : 0.8894
PR-AUC             : 0.4780
Balanced Accuracy  : 0.8017
MCC                : 0.3327

Confusion Matrix:
[[102172  11872]
 [  1189   2875]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9885    0.8959    0.9399    114044
       Fraud     0.1950    0.7074    0.3057      4064

    accuracy                         0.8894    118108
   macro avg     0.5917    0.8017    0.6228    118108
weighted avg     0.9612    0.8894    0.9181    118108


============================================================
LightGBM - Remove C + id
============================================================
Features: 385
Accuracy           : 0.8911
Precision          : 0.1989
Recall             : 0.7146
F1 Score           : 0.3112
ROC-AUC            : 0.8966
PR-AUC             : 0.4742
Balanced Accuracy  : 0.8060
MCC                : 0.3389

Confusion Matrix:
[[102346  11698]
 [  1160   2904]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9888    0.8974    0.9409    114044
       Fraud     0.1989    0.7146    0.3112      4064

    accuracy                         0.8911    118108
   macro avg     0.5938    0.8060    0.6260    118108
weighted avg     0.9616    0.8911    0.9192    118108


============================================================
LightGBM - Remove C + V
============================================================
Features: 84
Accuracy           : 0.8694
Precision          : 0.1690
Recall             : 0.7133
F1 Score           : 0.2732
ROC-AUC            : 0.8848
PR-AUC             : 0.3829
Balanced Accuracy  : 0.7942
MCC                : 0.3043

Confusion Matrix:
[[99786 14258]
 [ 1165  2899]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9885    0.8750    0.9283    114044
       Fraud     0.1690    0.7133    0.2732      4064

    accuracy                         0.8694    118108
   macro avg     0.5787    0.7942    0.6007    118108
weighted avg     0.9603    0.8694    0.9057    118108


============================================================
LightGBM - Remove D + M
============================================================
Features: 406
Accuracy           : 0.8988
Precision          : 0.2118
Recall             : 0.7131
F1 Score           : 0.3266
ROC-AUC            : 0.8947
PR-AUC             : 0.5093
Balanced Accuracy  : 0.8093
MCC                : 0.3523

Confusion Matrix:
[[103260  10784]
 [  1166   2898]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9888    0.9054    0.9453    114044
       Fraud     0.2118    0.7131    0.3266      4064

    accuracy                         0.8988    118108
   macro avg     0.6003    0.8093    0.6360    118108
weighted avg     0.9621    0.8988    0.9240    118108


============================================================
LightGBM - Remove D + id
============================================================
Features: 377
Accuracy           : 0.8988
Precision          : 0.2132
Recall             : 0.7217
F1 Score           : 0.3292
ROC-AUC            : 0.8996
PR-AUC             : 0.5135
Balanced Accuracy  : 0.8134
MCC                : 0.3562

Confusion Matrix:
[[103223  10821]
 [  1131   2933]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9892    0.9051    0.9453    114044
       Fraud     0.2132    0.7217    0.3292      4064

    accuracy                         0.8988    118108
   macro avg     0.6012    0.8134    0.6372    118108
weighted avg     0.9625    0.8988    0.9241    118108


============================================================
LightGBM - Remove D + V
============================================================
Features: 76
Accuracy           : 0.8940
Precision          : 0.2058
Recall             : 0.7281
F1 Score           : 0.3209
ROC-AUC            : 0.8998
PR-AUC             : 0.5077
Balanced Accuracy  : 0.8140
MCC                : 0.3501

Confusion Matrix:
[[102625  11419]
 [  1105   2959]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9893    0.8999    0.9425    114044
       Fraud     0.2058    0.7281    0.3209      4064

    accuracy                         0.8940    118108
   macro avg     0.5976    0.8140    0.6317    118108
weighted avg     0.9624    0.8940    0.9211    118108


============================================================
LightGBM - Remove M + id
============================================================
Features: 390
Accuracy           : 0.8937
Precision          : 0.2039
Recall             : 0.7197
F1 Score           : 0.3178
ROC-AUC            : 0.9019
PR-AUC             : 0.5086
Balanced Accuracy  : 0.8098
MCC                : 0.3458

Confusion Matrix:
[[102625  11419]
 [  1139   2925]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9890    0.8999    0.9423    114044
       Fraud     0.2039    0.7197    0.3178      4064

    accuracy                         0.8937    118108
   macro avg     0.5965    0.8098    0.6301    118108
weighted avg     0.9620    0.8937    0.9209    118108


============================================================
LightGBM - Remove M + V
============================================================
Features: 89
Accuracy           : 0.8883
Precision          : 0.1989
Recall             : 0.7426
F1 Score           : 0.3138
ROC-AUC            : 0.9058
PR-AUC             : 0.5070
Balanced Accuracy  : 0.8180
MCC                : 0.3465

Confusion Matrix:
[[101892  12152]
 [  1046   3018]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9898    0.8934    0.9392    114044
       Fraud     0.1989    0.7426    0.3138      4064

    accuracy                         0.8883    118108
   macro avg     0.5944    0.8180    0.6265    118108
weighted avg     0.9626    0.8883    0.9177    118108


============================================================
LightGBM - Remove id + V
============================================================
Features: 60
Accuracy           : 0.8927
Precision          : 0.2074
Recall             : 0.7505
F1 Score           : 0.3250
ROC-AUC            : 0.9108
PR-AUC             : 0.5020
Balanced Accuracy  : 0.8241
MCC                : 0.3579

Confusion Matrix:
[[102389  11655]
 [  1014   3050]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9902    0.8978    0.9417    114044
       Fraud     0.2074    0.7505    0.3250      4064

    accuracy                         0.8927    118108
   macro avg     0.5988    0.8241    0.6334    118108
weighted avg     0.9633    0.8927    0.9205    118108


============================================================
LightGBM - Remove C + D + M
============================================================
Features: 392
Accuracy           : 0.8925
Precision          : 0.1968
Recall             : 0.6897
F1 Score           : 0.3063
ROC-AUC            : 0.8807
PR-AUC             : 0.4770
Balanced Accuracy  : 0.7947
MCC                : 0.3300

Confusion Matrix:
[[102607  11437]
 [  1261   2803]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9879    0.8997    0.9417    114044
       Fraud     0.1968    0.6897    0.3063      4064

    accuracy                         0.8925    118108
   macro avg     0.5923    0.7947    0.6240    118108
weighted avg     0.9606    0.8925    0.9199    118108


============================================================
LightGBM - Remove C + D + id
============================================================
Features: 363
Accuracy           : 0.8847
Precision          : 0.1870
Recall             : 0.7020
F1 Score           : 0.2953
ROC-AUC            : 0.8833
PR-AUC             : 0.4687
Balanced Accuracy  : 0.7966
MCC                : 0.3224

Confusion Matrix:
[[101639  12405]
 [  1211   2853]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9882    0.8912    0.9372    114044
       Fraud     0.1870    0.7020    0.2953      4064

    accuracy                         0.8847    118108
   macro avg     0.5876    0.7966    0.6163    118108
weighted avg     0.9607    0.8847    0.9151    118108


============================================================
LightGBM - Remove C + D + V
============================================================
Features: 62
Accuracy           : 0.8430
Precision          : 0.1411
Recall             : 0.7005
F1 Score           : 0.2349
ROC-AUC            : 0.8533
PR-AUC             : 0.3150
Balanced Accuracy  : 0.7743
MCC                : 0.2657

Confusion Matrix:
[[96716 17328]
 [ 1217  2847]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9876    0.8481    0.9125    114044
       Fraud     0.1411    0.7005    0.2349      4064

    accuracy                         0.8430    118108
   macro avg     0.5643    0.7743    0.5737    118108
weighted avg     0.9584    0.8430    0.8892    118108


============================================================
LightGBM - Remove C + M + id
============================================================
Features: 376
Accuracy           : 0.8824
Precision          : 0.1843
Recall             : 0.7062
F1 Score           : 0.2923
ROC-AUC            : 0.8892
PR-AUC             : 0.4647
Balanced Accuracy  : 0.7974
MCC                : 0.3205

Confusion Matrix:
[[101343  12701]
 [  1194   2870]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9884    0.8886    0.9358    114044
       Fraud     0.1843    0.7062    0.2923      4064

    accuracy                         0.8824    118108
   macro avg     0.5863    0.7974    0.6141    118108
weighted avg     0.9607    0.8824    0.9137    118108


============================================================
LightGBM - Remove C + M + V
============================================================
Features: 75
Accuracy           : 0.8616
Precision          : 0.1581
Recall             : 0.6991
F1 Score           : 0.2579
ROC-AUC            : 0.8740
PR-AUC             : 0.3806
Balanced Accuracy  : 0.7832
MCC                : 0.2875

Confusion Matrix:
[[98920 15124]
 [ 1223  2841]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9878    0.8674    0.9237    114044
       Fraud     0.1581    0.6991    0.2579      4064

    accuracy                         0.8616    118108
   macro avg     0.5730    0.7832    0.5908    118108
weighted avg     0.9592    0.8616    0.9008    118108


============================================================
LightGBM - Remove C + id + V
============================================================
Features: 46
Accuracy           : 0.8697
Precision          : 0.1712
Recall             : 0.7251
F1 Score           : 0.2770
ROC-AUC            : 0.8853
PR-AUC             : 0.3496
Balanced Accuracy  : 0.8000
MCC                : 0.3099

Confusion Matrix:
[[99774 14270]
 [ 1117  2947]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9889    0.8749    0.9284    114044
       Fraud     0.1712    0.7251    0.2770      4064

    accuracy                         0.8697    118108
   macro avg     0.5800    0.8000    0.6027    118108
weighted avg     0.9608    0.8697    0.9060    118108


============================================================
LightGBM - Remove D + M + id
============================================================
Features: 368
Accuracy           : 0.8955
Precision          : 0.2060
Recall             : 0.7133
F1 Score           : 0.3197
ROC-AUC            : 0.8948
PR-AUC             : 0.5039
Balanced Accuracy  : 0.8077
MCC                : 0.3462

Confusion Matrix:
[[102870  11174]
 [  1165   2899]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9888    0.9020    0.9434    114044
       Fraud     0.2060    0.7133    0.3197      4064

    accuracy                         0.8955    118108
   macro avg     0.5974    0.8077    0.6315    118108
weighted avg     0.9619    0.8955    0.9220    118108


============================================================
LightGBM - Remove D + M + V
============================================================
Features: 67
Accuracy           : 0.8906
Precision          : 0.1956
Recall             : 0.7008
F1 Score           : 0.3059
ROC-AUC            : 0.8900
PR-AUC             : 0.4878
Balanced Accuracy  : 0.7991
MCC                : 0.3316

Confusion Matrix:
[[102334  11710]
 [  1216   2848]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9883    0.8973    0.9406    114044
       Fraud     0.1956    0.7008    0.3059      4064

    accuracy                         0.8906    118108
   macro avg     0.5919    0.7991    0.6232    118108
weighted avg     0.9610    0.8906    0.9188    118108


============================================================
LightGBM - Remove D + id + V
============================================================
Features: 38
Accuracy           : 0.8895
Precision          : 0.1988
Recall             : 0.7298
F1 Score           : 0.3125
ROC-AUC            : 0.8965
PR-AUC             : 0.4881
Balanced Accuracy  : 0.8125
MCC                : 0.3430

Confusion Matrix:
[[102092  11952]
 [  1098   2966]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9894    0.8952    0.9399    114044
       Fraud     0.1988    0.7298    0.3125      4064

    accuracy                         0.8895    118108
   macro avg     0.5941    0.8125    0.6262    118108
weighted avg     0.9622    0.8895    0.9183    118108


============================================================
LightGBM - Remove M + id + V
============================================================
Features: 51
Accuracy           : 0.8885
Precision          : 0.1998
Recall             : 0.7453
F1 Score           : 0.3152
ROC-AUC            : 0.9076
PR-AUC             : 0.4966
Balanced Accuracy  : 0.8195
MCC                : 0.3482

Confusion Matrix:
[[101915  12129]
 [  1035   3029]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9899    0.8936    0.9393    114044
       Fraud     0.1998    0.7453    0.3152      4064

    accuracy                         0.8885    118108
   macro avg     0.5949    0.8195    0.6272    118108
weighted avg     0.9628    0.8885    0.9179    118108


============================================================
LightGBM - Remove C + D + M + id
============================================================
Features: 354
Accuracy           : 0.8839
Precision          : 0.1844

In [15]:

# 3. ALL ABLATION EXPERIMENTS
for name, (X_train, X_valid) in ablation_datasets.items():
    xgb_results.append(
        run_xgboost(
            X_train, X_valid,
            y_train, y_valid,
            f"XGBoost - {name}"
        )
    )

    save_results()

============================================================
XGBoost - Remove C
============================================================
Features: 423
Accuracy           : 0.8971
Precision          : 0.2075
Recall             : 0.7055
F1 Score           : 0.3206
ROC-AUC            : 0.8933
PR-AUC             : 0.4763
Balanced Accuracy  : 0.8047
MCC                : 0.3456

Confusion Matrix:
[[103092  10952]
 [  1197   2867]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9885    0.9040    0.9444    114044
       Fraud     0.2075    0.7055    0.3206      4064

    accuracy                         0.8971    118108
   macro avg     0.5980    0.8047    0.6325    118108
weighted avg     0.9616    0.8971    0.9229    118108


============================================================
XGBoost - Remove D
============================================================
Features: 415
Accuracy           : 0.9083
Precision          : 0.2307
Recall             : 0.7133
F1 Score           : 0.3487
ROC-AUC            : 0.8990
PR-AUC             : 0.5213
Balanced Accuracy  : 0.8143
MCC                : 0.3716

Confusion Matrix:
[[104378   9666]
 [  1165   2899]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9890    0.9152    0.9507    114044
       Fraud     0.2307    0.7133    0.3487      4064

    accuracy                         0.9083    118108
   macro avg     0.6098    0.8143    0.6497    118108
weighted avg     0.9629    0.9083    0.9300    118108


============================================================
XGBoost - Remove M
============================================================
Features: 428
Accuracy           : 0.9101
Precision          : 0.2344
Recall             : 0.7116
F1 Score           : 0.3527
ROC-AUC            : 0.9018
PR-AUC             : 0.5216
Balanced Accuracy  : 0.8144
MCC                : 0.3748

Confusion Matrix:
[[104600   9444]
 [  1172   2892]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9889    0.9172    0.9517    114044
       Fraud     0.2344    0.7116    0.3527      4064

    accuracy                         0.9101    118108
   macro avg     0.6117    0.8144    0.6522    118108
weighted avg     0.9630    0.9101    0.9311    118108


============================================================
XGBoost - Remove id
============================================================
Features: 399
Accuracy           : 0.9096
Precision          : 0.2336
Recall             : 0.7141
F1 Score           : 0.3521
ROC-AUC            : 0.9039
PR-AUC             : 0.5165
Balanced Accuracy  : 0.8153
MCC                : 0.3747

Confusion Matrix:
[[104525   9519]
 [  1162   2902]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9890    0.9165    0.9514    114044
       Fraud     0.2336    0.7141    0.3521      4064

    accuracy                         0.9096    118108
   macro avg     0.6113    0.8153    0.6517    118108
weighted avg     0.9630    0.9096    0.9308    118108


============================================================
XGBoost - Remove V
============================================================
Features: 98
Accuracy           : 0.8997
Precision          : 0.2169
Recall             : 0.7335
F1 Score           : 0.3348
ROC-AUC            : 0.9076
PR-AUC             : 0.5137
Balanced Accuracy  : 0.8196
MCC                : 0.3633

Confusion Matrix:
[[103282  10762]
 [  1083   2981]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9896    0.9056    0.9458    114044
       Fraud     0.2169    0.7335    0.3348      4064

    accuracy                         0.8997    118108
   macro avg     0.6033    0.8196    0.6403    118108
weighted avg     0.9630    0.8997    0.9247    118108


============================================================
XGBoost - Remove C + D
============================================================
Features: 401
Accuracy           : 0.8936
Precision          : 0.2006
Recall             : 0.7005
F1 Score           : 0.3119
ROC-AUC            : 0.8830
PR-AUC             : 0.4771
Balanced Accuracy  : 0.8005
MCC                : 0.3369

Confusion Matrix:
[[102698  11346]
 [  1217   2847]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9883    0.9005    0.9424    114044
       Fraud     0.2006    0.7005    0.3119      4064

    accuracy                         0.8936    118108
   macro avg     0.5944    0.8005    0.6271    118108
weighted avg     0.9612    0.8936    0.9207    118108


============================================================
XGBoost - Remove C + M
============================================================
Features: 414
Accuracy           : 0.8970
Precision          : 0.2059
Recall             : 0.6981
F1 Score           : 0.3180
ROC-AUC            : 0.8879
PR-AUC             : 0.4711
Balanced Accuracy  : 0.8011
MCC                : 0.3419

Confusion Matrix:
[[103100  10944]
 [  1227   2837]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9882    0.9040    0.9443    114044
       Fraud     0.2059    0.6981    0.3180      4064

    accuracy                         0.8970    118108
   macro avg     0.5971    0.8011    0.6311    118108
weighted avg     0.9613    0.8970    0.9227    118108


============================================================
XGBoost - Remove C + id
============================================================
Features: 385
Accuracy           : 0.8915
Precision          : 0.1982
Recall             : 0.7069
F1 Score           : 0.3097
ROC-AUC            : 0.8917
PR-AUC             : 0.4707
Balanced Accuracy  : 0.8025
MCC                : 0.3361

Confusion Matrix:
[[102425  11619]
 [  1191   2873]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9885    0.8981    0.9411    114044
       Fraud     0.1982    0.7069    0.3097      4064

    accuracy                         0.8915    118108
   macro avg     0.5934    0.8025    0.6254    118108
weighted avg     0.9613    0.8915    0.9194    118108


============================================================
XGBoost - Remove C + V
============================================================
Features: 84
Accuracy           : 0.8808
Precision          : 0.1815
Recall             : 0.7020
F1 Score           : 0.2884
ROC-AUC            : 0.8814
PR-AUC             : 0.3828
Balanced Accuracy  : 0.7946
MCC                : 0.3162

Confusion Matrix:
[[101176  12868]
 [  1211   2853]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9882    0.8872    0.9349    114044
       Fraud     0.1815    0.7020    0.2884      4064

    accuracy                         0.8808    118108
   macro avg     0.5848    0.7946    0.6117    118108
weighted avg     0.9604    0.8808    0.9127    118108


============================================================
XGBoost - Remove D + M
============================================================
Features: 406
Accuracy           : 0.9085
Precision          : 0.2291
Recall             : 0.7018
F1 Score           : 0.3454
ROC-AUC            : 0.8932
PR-AUC             : 0.5158
Balanced Accuracy  : 0.8088
MCC                : 0.3666

Confusion Matrix:
[[104445   9599]
 [  1212   2852]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9885    0.9158    0.9508    114044
       Fraud     0.2291    0.7018    0.3454      4064

    accuracy                         0.9085    118108
   macro avg     0.6088    0.8088    0.6481    118108
weighted avg     0.9624    0.9085    0.9300    118108


============================================================
XGBoost - Remove D + id
============================================================
Features: 377
Accuracy           : 0.9070
Precision          : 0.2279
Recall             : 0.7136
F1 Score           : 0.3455
ROC-AUC            : 0.8994
PR-AUC             : 0.5142
Balanced Accuracy  : 0.8137
MCC                : 0.3689

Confusion Matrix:
[[104220   9824]
 [  1164   2900]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9890    0.9139    0.9499    114044
       Fraud     0.2279    0.7136    0.3455      4064

    accuracy                         0.9070    118108
   macro avg     0.6084    0.8137    0.6477    118108
weighted avg     0.9628    0.9070    0.9291    118108


============================================================
XGBoost - Remove D + V
============================================================
Features: 76
Accuracy           : 0.9052
Precision          : 0.2198
Recall             : 0.6890
F1 Score           : 0.3333
ROC-AUC            : 0.8903
PR-AUC             : 0.4932
Balanced Accuracy  : 0.8009
MCC                : 0.3537

Confusion Matrix:
[[104108   9936]
 [  1264   2800]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9880    0.9129    0.9490    114044
       Fraud     0.2198    0.6890    0.3333      4064

    accuracy                         0.9052    118108
   macro avg     0.6039    0.8009    0.6411    118108
weighted avg     0.9616    0.9052    0.9278    118108


============================================================
XGBoost - Remove M + id
============================================================
Features: 390
Accuracy           : 0.9064
Precision          : 0.2276
Recall             : 0.7190
F1 Score           : 0.3457
ROC-AUC            : 0.9017
PR-AUC             : 0.5151
Balanced Accuracy  : 0.8160
MCC                : 0.3701

Confusion Matrix:
[[104127   9917]
 [  1142   2922]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9892    0.9130    0.9496    114044
       Fraud     0.2276    0.7190    0.3457      4064

    accuracy                         0.9064    118108
   macro avg     0.6084    0.8160    0.6477    118108
weighted avg     0.9629    0.9064    0.9288    118108


============================================================
XGBoost - Remove M + V
============================================================
Features: 89
Accuracy           : 0.9013
Precision          : 0.2171
Recall             : 0.7175
F1 Score           : 0.3334
ROC-AUC            : 0.9025
PR-AUC             : 0.5011
Balanced Accuracy  : 0.8127
MCC                : 0.3591

Confusion Matrix:
[[103531  10513]
 [  1148   2916]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9890    0.9078    0.9467    114044
       Fraud     0.2171    0.7175    0.3334      4064

    accuracy                         0.9013    118108
   macro avg     0.6031    0.8127    0.6400    118108
weighted avg     0.9625    0.9013    0.9256    118108


============================================================
XGBoost - Remove id + V
============================================================
Features: 60
Accuracy           : 0.9003
Precision          : 0.2181
Recall             : 0.7340
F1 Score           : 0.3363
ROC-AUC            : 0.9078
PR-AUC             : 0.4986
Balanced Accuracy  : 0.8201
MCC                : 0.3647

Confusion Matrix:
[[103350  10694]
 [  1081   2983]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9896    0.9062    0.9461    114044
       Fraud     0.2181    0.7340    0.3363      4064

    accuracy                         0.9003    118108
   macro avg     0.6039    0.8201    0.6412    118108
weighted avg     0.9631    0.9003    0.9251    118108


============================================================
XGBoost - Remove C + D + M
============================================================
Features: 392
Accuracy           : 0.8891
Precision          : 0.1929
Recall             : 0.6976
F1 Score           : 0.3022
ROC-AUC            : 0.8781
PR-AUC             : 0.4694
Balanced Accuracy  : 0.7968
MCC                : 0.3277

Confusion Matrix:
[[102179  11865]
 [  1229   2835]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9881    0.8960    0.9398    114044
       Fraud     0.1929    0.6976    0.3022      4064

    accuracy                         0.8891    118108
   macro avg     0.5905    0.7968    0.6210    118108
weighted avg     0.9608    0.8891    0.9178    118108


============================================================
XGBoost - Remove C + D + id
============================================================
Features: 363
Accuracy           : 0.8892
Precision          : 0.1937
Recall             : 0.7025
F1 Score           : 0.3037
ROC-AUC            : 0.8821
PR-AUC             : 0.4654
Balanced Accuracy  : 0.7992
MCC                : 0.3300

Confusion Matrix:
[[102161  11883]
 [  1209   2855]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9883    0.8958    0.9398    114044
       Fraud     0.1937    0.7025    0.3037      4064

    accuracy                         0.8892    118108
   macro avg     0.5910    0.7992    0.6217    118108
weighted avg     0.9610    0.8892    0.9179    118108


============================================================
XGBoost - Remove C + D + V
============================================================
Features: 62
Accuracy           : 0.8703
Precision          : 0.1576
Recall             : 0.6373
F1 Score           : 0.2528
ROC-AUC            : 0.8437
PR-AUC             : 0.3187
Balanced Accuracy  : 0.7580
MCC                : 0.2718

Confusion Matrix:
[[100205  13839]
 [  1474   2590]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9855    0.8787    0.9290    114044
       Fraud     0.1576    0.6373    0.2528      4064

    accuracy                         0.8703    118108
   macro avg     0.5716    0.7580    0.5909    118108
weighted avg     0.9570    0.8703    0.9057    118108


============================================================
XGBoost - Remove C + M + id
============================================================
Features: 376
Accuracy           : 0.8911
Precision          : 0.1972
Recall             : 0.7052
F1 Score           : 0.3083
ROC-AUC            : 0.8879
PR-AUC             : 0.4693
Balanced Accuracy  : 0.8015
MCC                : 0.3346

Confusion Matrix:
[[102380  11664]
 [  1198   2866]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9884    0.8977    0.9409    114044
       Fraud     0.1972    0.7052    0.3083      4064

    accuracy                         0.8911    118108
   macro avg     0.5928    0.8015    0.6246    118108
weighted avg     0.9612    0.8911    0.9191    118108


============================================================
XGBoost - Remove C + M + V
============================================================
Features: 75
Accuracy           : 0.8736
Precision          : 0.1675
Recall             : 0.6732
F1 Score           : 0.2682
ROC-AUC            : 0.8686
PR-AUC             : 0.3765
Balanced Accuracy  : 0.7770
MCC                : 0.2925

Confusion Matrix:
[[100444  13600]
 [  1328   2736]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9870    0.8807    0.9308    114044
       Fraud     0.1675    0.6732    0.2682      4064

    accuracy                         0.8736    118108
   macro avg     0.5772    0.7770    0.5995    118108
weighted avg     0.9588    0.8736    0.9080    118108


============================================================
XGBoost - Remove C + id + V
============================================================
Features: 46
Accuracy           : 0.8837
Precision          : 0.1837
Recall             : 0.6907
F1 Score           : 0.2902
ROC-AUC            : 0.8837
PR-AUC             : 0.3502
Balanced Accuracy  : 0.7907
MCC                : 0.3157

Confusion Matrix:
[[101570  12474]
 [  1257   2807]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9878    0.8906    0.9367    114044
       Fraud     0.1837    0.6907    0.2902      4064

    accuracy                         0.8837    118108
   macro avg     0.5857    0.7907    0.6134    118108
weighted avg     0.9601    0.8837    0.9144    118108


============================================================
XGBoost - Remove D + M + id
============================================================
Features: 368
Accuracy           : 0.9056
Precision          : 0.2234
Recall             : 0.7045
F1 Score           : 0.3393
ROC-AUC            : 0.8950
PR-AUC             : 0.5083
Balanced Accuracy  : 0.8086
MCC                : 0.3618

Confusion Matrix:
[[104094   9950]
 [  1201   2863]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9886    0.9128    0.9492    114044
       Fraud     0.2234    0.7045    0.3393      4064

    accuracy                         0.9056    118108
   macro avg     0.6060    0.8086    0.6442    118108
weighted avg     0.9623    0.9056    0.9282    118108


============================================================
XGBoost - Remove D + M + V
============================================================
Features: 67
Accuracy           : 0.9025
Precision          : 0.2104
Recall             : 0.6661
F1 Score           : 0.3197
ROC-AUC            : 0.8861
PR-AUC             : 0.4897
Balanced Accuracy  : 0.7885
MCC                : 0.3375

Confusion Matrix:
[[103882  10162]
 [  1357   2707]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9871    0.9109    0.9475    114044
       Fraud     0.2104    0.6661    0.3197      4064

    accuracy                         0.9025    118108
   macro avg     0.5987    0.7885    0.6336    118108
weighted avg     0.9604    0.9025    0.9259    118108


============================================================
XGBoost - Remove D + id + V
============================================================
Features: 38
Accuracy           : 0.9075
Precision          : 0.2236
Recall             : 0.6826
F1 Score           : 0.3368
ROC-AUC            : 0.8915
PR-AUC             : 0.4819
Balanced Accuracy  : 0.7991
MCC                : 0.3555

Confusion Matrix:
[[104410   9634]
 [  1290   2774]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9878    0.9155    0.9503    114044
       Fraud     0.2236    0.6826    0.3368      4064

    accuracy                         0.9075    118108
   macro avg     0.6057    0.7991    0.6436    118108
weighted avg     0.9615    0.9075    0.9292    118108


============================================================
XGBoost - Remove M + id + V
============================================================
Features: 51
Accuracy           : 0.9023
Precision          : 0.2201
Recall             : 0.7237
F1 Score           : 0.3376
ROC-AUC            : 0.9044
PR-AUC             : 0.4907
Balanced Accuracy  : 0.8162
MCC                : 0.3639

Confusion Matrix:
[[103624  10420]
 [  1123   2941]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9893    0.9086    0.9472    114044
       Fraud     0.2201    0.7237    0.3376      4064

    accuracy                         0.9023    118108
   macro avg     0.6047    0.8162    0.6424    118108
weighted avg     0.9628    0.9023    0.9263    118108


============================================================
XGBoost - Remove C + D + M + id
============================================================
Features: 354
Accuracy           : 0.8836
Precision          : 0.1840
Recall             : 0.6939

In [16]:
# RESULTS

metrics = [
    "Model",
    "Features",
    "Accuracy",
    "Precision",
    "Recall",
    "F1",
    "ROC-AUC",
    "PR-AUC",
    "Balanced Accuracy",
    "MCC",
]


rf_results_df = pd.DataFrame(rf_results)
lgb_results_df = pd.DataFrame(lgb_results)
xgb_results_df = pd.DataFrame(xgb_results)

print("===== RANDOM FOREST =====")
display(
    rf_results_df[metrics]
    .sort_values("ROC-AUC", ascending=False)
    .reset_index(drop=True)
)

print("===== LIGHTGBM =====")
display(
    lgb_results_df[metrics]
    .sort_values("ROC-AUC", ascending=False)
    .reset_index(drop=True)
)

print("===== XGBOOST =====")
display(
    xgb_results_df[metrics]
    .sort_values("ROC-AUC", ascending=False)
    .reset_index(drop=True)
)

===== RANDOM FOREST =====

,Model,Features,Accuracy,Precision,Recall,F1,ROC-AUC,PR-AUC,Balanced Accuracy,MCC
0,RF - Remove V,98,0.973312561384496,0.827586206896552,0.283464566929134,0.422287390029326,0.913281442459217,0.544476096233882,0.640680058007726,0.475215710024012
1,RF - Remove id + V,60,0.973583499847597,0.833333333333333,0.290354330708661,0.430656934306569,0.911376661509910,0.544989919129918,0.644142476988437,0.482817361635724
2,RF - Remove D + V,76,0.975420801300505,0.847813061713601,0.348179133858268,0.493633350776208,0.909096788982813,0.569556696496112,0.672975961653977,0.534258472247884
3,RF - Feature Engineering,439,0.974201578216548,0.814860681114551,0.323818897637795,0.463461877091037,0.907364772544621,0.534104626655642,0.660598551270583,0.504136928568910
4,RF - Remove D + id + V,38,0.974997459951908,0.796583021890016,0.367125984251969,0.502610746168098,0.905963568039908,0.559537161310039,0.681892584213249,0.530787529106364
5,RF - Baseline,437,0.973964507061334,0.805813234384663,0.320620078740157,0.458722055976061,0.905585130001972,0.527852880516008,0.658933377730711,0.498605405730541
6,RF - Remove M + V,89,0.973134758018085,0.821196827685652,0.280265748031496,0.417904971564851,0.905517049711715,0.528821995292930,0.639045574377012,0.470530203394801
7,RF - Remove M + id + V,51,0.973295627730552,0.826398852223816,0.283464566929134,0.422132649322096,0.904837250099906,0.530290409729902,0.640671289462252,0.474849156502682
8,RF - Remove D,415,0.974404782063874,0.804920913884007,0.338090551181102,0.476173973314850,0.904618119531224,0.527224645188008,0.667585312769184,0.511898555498119
9,RF - Remove D + M + V,67,0.974997459951908,0.827728613569321,0.345226377952756,0.487237367598541,0.903222578764668,0.562978798551109,0.671332981337221,0.525168230642269
10,RF - Remove id,399,0.974116909946828,0.806079027355623,0.326279527559055,0.464529689963216,0.903148092516854,0.527526179737262,0.661741180776476,0.503137558127239
11,RF - Remove M,428,0.974032241677109,0.807526218383714,0.322096456692913,0.460510114335972,0.901756710552316,0.523310719169773,0.659680335252563,0.500338893802179
12,RF - Remove D + M + id + V,29,0.974430182544790,0.786184210526316,0.352854330708661,0.487092391304348,0.898393190149085,0.544643162936209,0.674717298986964,0.516543112330837
13,RF - Remove D + id,377,0.973939106580418,0.771177117711771,0.344980314960630,0.476708602516151,0.897983537901658,0.515824072292802,0.670666300021790,0.505385426846373
14,RF - Remove M + id,390,0.974006841196193,0.802679658952497,0.324311023622047,0.461969856291623,0.897969031180326,0.517204201556957,0.660735007444288,0.500457709972475
15,RF - Remove D + M,406,0.974210045043519,0.793540945790081,0.338582677165354,0.474646429803380,0.896177015797122,0.513727101539298,0.667721768942889,0.508370068600717
16,RF - Remove C,423,0.972889220035899,0.793997271487040,0.286417322834646,0.420976491862568,0.891637462778560,0.487854537939310,0.641884611050798,0.467179627467854
17,RF - Remove D + M + id,368,0.973676634944288,0.760501909438080,0.343011811023622,0.472782770900458,0.890991826835312,0.502350589019891,0.669581209780339,0.500145526445434
18,RF - Remove C + V,84,0.968486470010499,0.751470588235294,0.125738188976378,0.215430016863406,0.889434192040329,0.407648953766888,0.562128152395663,0.299358239472387
19,RF - Remove C + D,401,0.973058556575338,0.783419023136247,0.299950787401575,0.433807829181495,0.889381471807952,0.486109869400173,0.648497893788473,0.474786868034476
20,RF - Remove C + id,385,0.972880753208927,0.789509078681910,0.288877952755905,0.422986849216357,0.888954797060645,0.482503088884546,0.643066699011322,0.467775808391211
21,RF - Remove C + M,414,0.972762217631321,0.792270531400966,0.282480314960630,0.416470161436604,0.887900421540919,0.479891974274923,0.639920491386527,0.463373368880321
22,RF - Remove C + M + id,376,0.972652148880686,0.779116465863454,0.286417322834646,0.418855703490464,0.884233134902415,0.476329059378009,0.641761851414166,0.462436172062223
23,RF - Remove C + D + M,392,0.972813018593152,0.771483131763208,0.298228346456693,0.430168589174800,0.881830202830266,0.472311203873286,0.647540219315822,0.469497713164028
24,RF - Remove C + id + V,46,0.968029261354015,0.730031948881789,0.112450787401575,0.194882729211087,0.880807008077004,0.376719618390279,0.555484451608262,0.278574610342649
25,RF - Remove C + D + id,363,0.972508212822163,0.741859088217880,0.308316929133858,0.435598818007996,0.880262827484460,0.469429725710412,0.652246921653668,0.467481930880770
26,RF - Remove C + D + M + id,354,0.972321942628780,0.733961153619776,0.306840551181102,0.432760714905431,0.873398304558580,0.456698242705083,0.651438584313500,0.463649332005760
27,RF - Remove C + M + V,75,0.968139330104650,0.736263736263736,0.115403543307087,0.199532014465007,0.873031979368648,0.378060594094653,0.556965213833754,0.283542228844671
28,RF - Remove C + D + V,62,0.969578690689877,0.774795799299883,0.163385826771654,0.269863848811217,0.865380401812382,0.393522710044290,0.580846748747617,0.347261739841069
29,RF - Remove C + M + id + V,37,0.967876858468520,0.720588235294118,0.108513779527559,0.188622754491018,0.859976786743036,0.347733037168064,0.553507179125780,0.271686381612987
30,RF - Remove C + D + M + V,53,0.969138415687337,0.743321718931475,0.157480314960630,0.259898477157360,0.846666323505267,0.362848076030866,0.577771233205474,0.333280271365534
31,RF - Remove C + D + id + V,24,0.966945507501609,0.567911714770798,0.164616141732283,0.255246089278901,0.837712239363616,0.317114808745556,0.580076476043091,0.293773352012287
32,RF - Remove C + D + M + id + V,15,0.966649168557591,0.552653748946925,0.161417322834646,0.249857170062845,0.825685585902471,0.291687008978951,0.578380612594062,0.286470627535491

===== LIGHTGBM =====

,Model,Features,Accuracy,Precision,Recall,F1,ROC-AUC,PR-AUC,Balanced Accuracy,MCC
0,LightGBM - Remove id + V,60,0.892733769092695,0.207412444746685,0.750492125984252,0.325003995950770,0.910764810573872,0.502023207760918,0.824147364244274,0.357920420227433
1,LightGBM - Remove V,98,0.893140176787347,0.207852509388870,0.749015748031496,0.325404885349297,0.909820855293246,0.517411770543492,0.823645925995686,0.357994198789815
2,LightGBM - Remove id,399,0.898897619128255,0.215199942150553,0.732283464566929,0.332644050746102,0.908226082558065,0.514904765739761,0.818559220270557,0.361193086066857
3,LightGBM - Remove M + id + V,51,0.888542689741592,0.199828473413379,0.745324803149606,0.315159712829050,0.907620791849022,0.496626040232651,0.819485557549690,0.348225178507632
4,LightGBM - Remove M + V,89,0.888254817624547,0.198945286750165,0.742618110236220,0.313819278361235,0.905802493484349,0.506994896843176,0.818031372820050,0.346523248077533
5,LightGBM - Baseline,437,0.900836522504826,0.217994100294985,0.727362204724409,0.335451656831593,0.905724299375956,0.520272380209855,0.817190274260770,0.362723103855104
6,LightGBM - Feature Engineering,439,0.901674738375047,0.219138328744698,0.724655511811024,0.336513740501628,0.904996154095242,0.517520457318350,0.816319197805130,0.363141683120397
7,LightGBM - Remove D,415,0.896865580654994,0.210830067687923,0.728100393700787,0.326979391126582,0.902094653401837,0.520608047489786,0.815489992017171,0.355429448581254
8,LightGBM - Remove M + id,390,0.893673586886578,0.203918014500837,0.719734251968504,0.317796610169492,0.901934701884644,0.508643137442550,0.809803115602294,0.345756502335839
9,LightGBM - Remove D + V,76,0.893961459003624,0.205800528585339,0.728100393700787,0.320897950330767,0.899830904728165,0.507718399887002,0.813986186468436,0.350067811520352
10,LightGBM - Remove D + id,377,0.898804484031564,0.213247055402065,0.721702755905512,0.329217645078011,0.899582055176866,0.513477601434705,0.813409162667427,0.356193257903947
11,LightGBM - Remove M,428,0.897610661428523,0.210207175341081,0.716535433070866,0.325054417592231,0.899170586218001,0.514868334080586,0.810299388521684,0.351563372831298
12,LightGBM - Remove C + id,385,0.891133538795001,0.198876866182715,0.714566929133858,0.311153969784635,0.896568672460512,0.474170527173570,0.805996242091393,0.338898950699066
13,LightGBM - Remove D + id + V,38,0.889507908016392,0.198820217187291,0.729822834645669,0.312506585185966,0.896473368468849,0.488078584404291,0.812510589572142,0.342952281680114
14,LightGBM - Remove D + M + id,368,0.895527821993430,0.205997299793932,0.713336614173228,0.319678006285494,0.894783120211649,0.503899620449517,0.807678443525182,0.346223909729383
15,LightGBM - Remove D + M,406,0.898821417685508,0.211811138722409,0.713090551181102,0.326608813253691,0.894747227215038,0.509312180404995,0.809265278396486,0.352285781824486
16,LightGBM - Remove C,423,0.893910658041792,0.202738764044944,0.710383858267717,0.315450174825175,0.894063662565864,0.481029068944438,0.805417280752532,0.341932823822867
17,LightGBM - Remove D + M + V,67,0.890557794560910,0.195631268031323,0.700787401574803,0.305874771775320,0.889961924058458,0.487794728767997,0.799053867039024,0.331639750304154
18,LightGBM - Remove C + M,414,0.889414772919701,0.194954906082593,0.707431102362205,0.305672213066823,0.889365210946003,0.477975034439629,0.801665465249357,0.332689021390543
19,LightGBM - Remove D + M + id + V,29,0.890845666677956,0.195670159955874,0.698326771653543,0.305687203791469,0.889245429896238,0.482637933665030,0.798016460078815,0.331017657202519
20,LightGBM - Remove C + M + id,376,0.882353439225116,0.184316999550446,0.706200787401575,0.292335115864528,0.889167371717561,0.464733043666893,0.797415745670203,0.320485560629114
21,LightGBM - Remove C + D,401,0.892395096013818,0.199972235718748,0.708907480314961,0.311948459747713,0.885708135218290,0.481786200381809,0.803920612592681,0.338551678777959
22,LightGBM - Remove C + id + V,46,0.869720933383005,0.171168031596678,0.725147637795276,0.276960669141488,0.885250671311556,0.349599765519133,0.800010246942954,0.309937554066590
23,LightGBM - Remove C + V,84,0.869416127612016,0.168968933962814,0.713336614173228,0.273219923660525,0.884758112725590,0.382863050965340,0.794157346404772,0.304331409075340
24,LightGBM - Remove C + D + id,363,0.884715683950283,0.186983877310263,0.702017716535433,0.295311044405341,0.883270219584056,0.468746183295302,0.796621954967236,0.322400276525453
25,LightGBM - Remove C + D + M,392,0.892488231110509,0.196839887640449,0.689714566929134,0.306271853146853,0.880728643517062,0.476997342903064,0.794714356173346,0.329950262732981
26,LightGBM - Remove C + D + M + id,354,0.883894401734006,0.184363755315669,0.693405511811024,0.291281203162954,0.880528188180995,0.465205954284389,0.792044027695347,0.317185655482535
27,LightGBM - Remove C + M + V,75,0.861592779489958,0.158140829390481,0.699064960629921,0.257932725044260,0.873996814963944,0.380621993866812,0.783224739443017,0.287508270670916
28,LightGBM - Remove C + M + id + V,37,0.862329393436516,0.158107198923525,0.693897637795276,0.257534246575342,0.873588140115902,0.348319786643507,0.781114579481272,0.286212017864027
29,LightGBM - Remove C + D + V,62,0.842982693805669,0.141115241635688,0.700541338582677,0.234910681133710,0.853275465780648,0.314950085654866,0.774299991307403,0.265703673549355
30,LightGBM - Remove C + D + id + V,24,0.845641277474854,0.139571566681932,0.674950787401575,0.231310874056584,0.845057570506700,0.233263511505863,0.763337341720850,0.257763961642986
31,LightGBM - Remove C + D + M + V,53,0.862202391031937,0.147752841400796,0.630167322834646,0.239379352245642,0.835084549664075,0.301460256947328,0.750319184548746,0.257883721858098
32,LightGBM - Remove C + D + M + id + V,15,0.856241744843702,0.138902868646200,0.611220472440945,0.226363512097325,0.819194094032501,0.212543072404930,0.738096820345898,0.242152212214002

===== XGBOOST =====

,Model,Features,Accuracy,Precision,Recall,F1,ROC-AUC,PR-AUC,Balanced Accuracy,MCC
0,XGBoost - Remove id + V,60,0.900303112405595,0.218103385245302,0.734005905511811,0.336283185840708,0.907801848072798,0.498642447118692,0.820117540108156,0.364705569166280
1,XGBoost - Remove V,98,0.899710434517560,0.216910427126537,0.733513779527559,0.334812152524288,0.907587326168764,0.513711761963649,0.819573346569925,0.363325102429128
2,XGBoost - Remove M + id + V,51,0.902267416263081,0.220118254621660,0.723671259842520,0.337560975609756,0.904447913950949,0.490735293956568,0.816151508003404,0.363871503270599
3,XGBoost - Remove id,399,0.909565821112880,0.233636583205861,0.714074803149606,0.352077646345162,0.903891834114240,0.516510454474004,0.815303509392838,0.374699233363434
4,XGBoost - Feature Engineering,439,0.912580011514885,0.239537399118063,0.708415354330709,0.358017782751974,0.902735457367332,0.521707797253226,0.814135424350651,0.378783134971774
5,XGBoost - Remove M + V,89,0.901268330680394,0.217142006106188,0.717519685039370,0.333390499056766,0.902533531616958,0.501082004390631,0.812667983237303,0.359066475576069
6,XGBoost - Remove M,428,0.910116164866055,0.234435797665370,0.711614173228346,0.352682926829268,0.901766129618572,0.521579079622235,0.814402014887471,0.374762258976776
7,XGBoost - Remove M + id,390,0.906365360517493,0.227587818365916,0.718996062992126,0.345737443057445,0.901716939243577,0.515101021794309,0.816019198764836,0.370118408058816
8,XGBoost - Baseline,437,0.910971314390219,0.236500285924353,0.712352362204724,0.355105795768169,0.901697122632872,0.516953690398855,0.815200768103870,0.377000200309703
9,XGBoost - Remove D + id,377,0.906966505232499,0.227915749764225,0.713582677165354,0.345484870145342,0.899393257432136,0.514247409697822,0.813720243215977,0.368881129852313
10,XGBoost - Remove D,415,0.908295797067091,0.230720254675686,0.713336614173228,0.348667989656624,0.899015310251507,0.521259963661999,0.814289926812334,0.371601590439809
11,XGBoost - Remove D + M + id,368,0.905586412436075,0.223444938734098,0.704478346456693,0.339278307756118,0.894988500302895,0.508341681772705,0.808615659496804,0.361769323153565
12,XGBoost - Remove C,423,0.897136519118095,0.207467978869672,0.705462598425197,0.320639713694570,0.893311855805343,0.476292822386885,0.804714744198744,0.345604170764080
13,XGBoost - Remove D + M,406,0.908465133606530,0.229057906995422,0.701771653543307,0.345382985165001,0.893210328174552,0.515785169425600,0.808801192770742,0.366581700071986
14,XGBoost - Remove C + id,385,0.891539946489654,0.198247308860061,0.706938976377953,0.309657253718474,0.891704833213635,0.470691300349558,0.802528623259651,0.336149107859140
15,XGBoost - Remove D + id + V,38,0.907508382158702,0.223565441650548,0.682578740157480,0.336813987372511,0.891472892887453,0.481935148231572,0.799051286532039,0.355549731545159
16,XGBoost - Remove D + V,76,0.905171537914451,0.219849246231156,0.688976377952756,0.333333333333333,0.890323239267438,0.493228182157839,0.800926055063151,0.353690765579415
17,XGBoost - Remove C + M,414,0.896950248924713,0.205863144909658,0.698080708661417,0.317960212944802,0.887896570198973,0.471119746107737,0.801058873498749,0.341865891224738
18,XGBoost - Remove C + M + id,376,0.891099671487113,0.197247075017206,0.705216535433071,0.308271485425406,0.887862065627316,0.469344140063348,0.801470110514052,0.334596010606903
19,XGBoost - Remove D + M + V,67,0.902470620110407,0.210350454580776,0.666092519685039,0.319730703360302,0.886082894523443,0.489747711346769,0.788493280290768,0.337534376909551
20,XGBoost - Remove C + id + V,46,0.883741998848512,0.183692166743014,0.690698818897638,0.290204187128457,0.883699315174872,0.350170639641512,0.790659991329496,0.315717642877885
21,XGBoost - Remove D + M + id + V,29,0.920784366850679,0.242255990648743,0.611958661417323,0.347103977669225,0.883066493304353,0.470840363302730,0.771874073088795,0.351816547921974
22,XGBoost - Remove C + D,401,0.893631252751719,0.200591841048404,0.700541338582677,0.311880374650819,0.882984918213981,0.477144727281143,0.800526710819170,0.336937944270967
23,XGBoost - Remove C + D + id,363,0.889152301283571,0.193716922241824,0.702509842519685,0.303691096691841,0.882063054748588,0.465420961387074,0.799156608327992,0.330008504914803
24,XGBoost - Remove C + V,84,0.880795543062282,0.181477005279562,0.702017716535433,0.288400303260046,0.881426676050506,0.382774108471573,0.794592036690080,0.316156107615115
25,XGBoost - Remove C + D + M,392,0.889135367629627,0.192857142857143,0.697588582677165,0.302174376465572,0.878141983015535,0.469367744536154,0.796774895315995,0.327743803788571
26,XGBoost - Remove C + D + M + id,354,0.883581129136045,0.184001043977554,0.693897637795276,0.290871583290356,0.876511892288016,0.458470571366366,0.792119104050737,0.316905723782015
27,XGBoost - Remove C + M + id + V,37,0.872819792054730,0.165598486235732,0.667568897637795,0.265369002787695,0.869633071929414,0.342707418570170,0.773851440506317,0.288833478670310
28,XGBoost - Remove C + M + V,75,0.873607206963119,0.167482859941234,0.673228346456693,0.268235294117647,0.868586180095706,0.376485704262033,0.776988064007344,0.292494095708605
29,XGBoost - Remove C + D + V,62,0.870347478578928,0.157648061354921,0.637303149606299,0.252769238276485,0.843740972540782,0.318740817337699,0.757977624398043,0.271771497402489
30,XGBoost - Remove C + D + id + V,24,0.875884783418566,0.160699417152373,0.617372047244094,0.255018549575647,0.840464846314325,0.239303478535696,0.751234513678517,0.270413174910119
31,XGBoost - Remove C + D + M + id + V,15,0.886044975784875,0.162220464514273,0.555118110236220,0.251071170218686,0.815674035458272,0.218846930109057,0.726477893461206,0.256162888750052
32,XGBoost - Remove C + D + M + V,53,0.873268533884242,0.151673907487861,0.584153543307087,0.240819638871982,0.813224021000528,0.286967193275326,0.733862398253803,0.251448962018508

In [17]:
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.pipeline import Pipeline


def get_sampling_variants(X_train, y_train):
    variants = {
        "Original": (X_train, y_train),
        "SMOTE": SMOTE(random_state=42).fit_resample(X_train, y_train),
        "Undersampling": RandomUnderSampler(random_state=42).fit_resample(
            X_train, y_train
        ),
        "SMOTE + Undersampling": Pipeline(
            [
                ("under", RandomUnderSampler(sampling_strategy=0.1, random_state=42)),
                ("smote", SMOTE(sampling_strategy=0.5, random_state=42)),
            ]
        ).fit_resample(X_train, y_train),
    }

    return variants

In [18]:
# ALL FEATURE CONFIGURATIONS
feature_datasets = {
    "Baseline": (X_train_baseline, X_valid_baseline),
    "Feature Engineering": (X_train_features, X_valid_features),
    **{
        name: (X_train, X_valid)
        for name, (X_train, X_valid) in ablation_datasets.items()
    },
}

In [19]:
# RUN EXPERIMENTS


for feature_name, (X_train, X_valid) in feature_datasets.items():

    sampling_variants = get_sampling_variants(X_train, y_train)

    for sampling_name, (X_sampled, y_sampled) in sampling_variants.items():

        experiment_name = f"{feature_name} - {sampling_name}"

        print(f"\n===== {experiment_name} =====")
        print(
            f"Train samples: "
            f"{len(y_sampled):,} | "
            f"Fraud rate: {y_sampled.mean():.4f}"
        )

        # Random Forest
        rf_results.append(
            run_random_forest(
                X_sampled, X_valid, y_sampled, y_valid, f"RF - {experiment_name}"
            )
        )
        save_results()

        # LightGBM
        lgb_results.append(
            run_lightgbm(
                X_sampled, X_valid, y_sampled, y_valid, f"LightGBM - {experiment_name}"
            )
        )
        save_results()

        # XGBoost
        xgb_results.append(
            run_xgboost(
                X_sampled, X_valid, y_sampled, y_valid, f"XGBoost - {experiment_name}"
            )
        )
        save_results()

===== Baseline - Original =====
Train samples: 472,432 | Fraud rate: 0.0351

============================================================
RF - Baseline - Original
============================================================
Features: 437
Accuracy           : 0.9740
Precision          : 0.8058
Recall             : 0.3206
F1 Score           : 0.4587
ROC-AUC            : 0.9056
PR-AUC             : 0.5279
Balanced Accuracy  : 0.6589
MCC                : 0.4986

Confusion Matrix:
[[113730    314]
 [  2761   1303]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9763    0.9972    0.9867    114044
       Fraud     0.8058    0.3206    0.4587      4064

    accuracy                         0.9740    118108
   macro avg     0.8911    0.6589    0.7227    118108
weighted avg     0.9704    0.9740    0.9685    118108


============================================================
LightGBM - Baseline - Original
============================================================
Features: 437
Accuracy           : 0.9008
Precision          : 0.2180
Recall             : 0.7274
F1 Score           : 0.3355
ROC-AUC            : 0.9057
PR-AUC             : 0.5203
Balanced Accuracy  : 0.8172
MCC                : 0.3627

Confusion Matrix:
[[103440  10604]
 [  1108   2956]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9894    0.9070    0.9464    114044
       Fraud     0.2180    0.7274    0.3355      4064

    accuracy                         0.9008    118108
   macro avg     0.6037    0.8172    0.6409    118108
weighted avg     0.9629    0.9008    0.9254    118108


============================================================
XGBoost - Baseline - Original
============================================================
Features: 437
Accuracy           : 0.9110
Precision          : 0.2365
Recall             : 0.7124
F1 Score           : 0.3551
ROC-AUC            : 0.9017
PR-AUC             : 0.5170
Balanced Accuracy  : 0.8152
MCC                : 0.3770

Confusion Matrix:
[[104698   9346]
 [  1169   2895]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9890    0.9180    0.9522    114044
       Fraud     0.2365    0.7124    0.3551      4064

    accuracy                         0.9110    118108
   macro avg     0.6127    0.8152    0.6536    118108
weighted avg     0.9631    0.9110    0.9316    118108


===== Baseline - SMOTE =====
Train samples: 911,666 | Fraud rate: 0.5000

============================================================
RF - Baseline - SMOTE
============================================================
Features: 437
Accuracy           : 0.9741
Precision          : 0.8208
Recall             : 0.3167
F1 Score           : 0.4570
ROC-AUC            : 0.8894
PR-AUC             : 0.4937
Balanced Accuracy  : 0.6571
MCC                : 0.5004

Confusion Matrix:
[[113763    281]
 [  2777   1287]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9762    0.9975    0.9867    114044
       Fraud     0.8208    0.3167    0.4570      4064

    accuracy                         0.9741    118108
   macro avg     0.8985    0.6571    0.7219    118108
weighted avg     0.9708    0.9741    0.9685    118108


============================================================
LightGBM - Baseline - SMOTE
============================================================
Features: 437
Accuracy           : 0.9735
Precision          : 0.7395
Recall             : 0.3541
F1 Score           : 0.4789
ROC-AUC            : 0.8974
PR-AUC             : 0.5129
Balanced Accuracy  : 0.6748
MCC                : 0.5006

Confusion Matrix:
[[113537    507]
 [  2625   1439]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9774    0.9956    0.9864    114044
       Fraud     0.7395    0.3541    0.4789      4064

    accuracy                         0.9735    118108
   macro avg     0.8584    0.6748    0.7326    118108
weighted avg     0.9692    0.9735    0.9689    118108


============================================================
XGBoost - Baseline - SMOTE
============================================================
Features: 437
Accuracy           : 0.9735
Precision          : 0.7415
Recall             : 0.3529
F1 Score           : 0.4782
ROC-AUC            : 0.8912
PR-AUC             : 0.5069
Balanced Accuracy  : 0.6742
MCC                : 0.5005

Confusion Matrix:
[[113544    500]
 [  2630   1434]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9774    0.9956    0.9864    114044
       Fraud     0.7415    0.3529    0.4782      4064

    accuracy                         0.9735    118108
   macro avg     0.8594    0.6742    0.7323    118108
weighted avg     0.9692    0.9735    0.9689    118108


===== Baseline - Undersampling =====
Train samples: 33,198 | Fraud rate: 0.5000

============================================================
RF - Baseline - Undersampling
============================================================
Features: 437
Accuracy           : 0.8695
Precision          : 0.1741
Recall             : 0.7463
F1 Score           : 0.2824
ROC-AUC            : 0.8934
PR-AUC             : 0.4604
Balanced Accuracy  : 0.8101
MCC                : 0.3188

Confusion Matrix:
[[99660 14384]
 [ 1031  3033]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9898    0.8739    0.9282    114044
       Fraud     0.1741    0.7463    0.2824      4064

    accuracy                         0.8695    118108
   macro avg     0.5820    0.8101    0.6053    118108
weighted avg     0.9617    0.8695    0.9060    118108


============================================================
LightGBM - Baseline - Undersampling
============================================================
Features: 437
Accuracy           : 0.8825
Precision          : 0.1931
Recall             : 0.7598
F1 Score           : 0.3079
ROC-AUC            : 0.9079
PR-AUC             : 0.5062
Balanced Accuracy  : 0.8233
MCC                : 0.3445

Confusion Matrix:
[[101139  12905]
 [   976   3088]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9904    0.8868    0.9358    114044
       Fraud     0.1931    0.7598    0.3079      4064

    accuracy                         0.8825    118108
   macro avg     0.5918    0.8233    0.6219    118108
weighted avg     0.9630    0.8825    0.9142    118108


============================================================
XGBoost - Baseline - Undersampling
============================================================
Features: 437
Accuracy           : 0.8843
Precision          : 0.1972
Recall             : 0.7692
F1 Score           : 0.3139
ROC-AUC            : 0.9091
PR-AUC             : 0.5124
Balanced Accuracy  : 0.8288
MCC                : 0.3516

Confusion Matrix:
[[101315  12729]
 [   938   3126]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9908    0.8884    0.9368    114044
       Fraud     0.1972    0.7692    0.3139      4064

    accuracy                         0.8843    118108
   macro avg     0.5940    0.8288    0.6253    118108
weighted avg     0.9635    0.8843    0.9154    118108


===== Baseline - SMOTE + Undersampling =====
Train samples: 248,985 | Fraud rate: 0.3333

============================================================
RF - Baseline - SMOTE + Undersampling
============================================================
Features: 437
Accuracy           : 0.9696
Precision          : 0.5772
Recall             : 0.4407
F1 Score           : 0.4998
ROC-AUC            : 0.8957
PR-AUC             : 0.5068
Balanced Accuracy  : 0.7146
MCC                : 0.4891

Confusion Matrix:
[[112732   1312]
 [  2273   1791]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9802    0.9885    0.9843    114044
       Fraud     0.5772    0.4407    0.4998      4064

    accuracy                         0.9696    118108
   macro avg     0.7787    0.7146    0.7421    118108
weighted avg     0.9664    0.9696    0.9677    118108


============================================================
LightGBM - Baseline - SMOTE + Undersampling
============================================================
Features: 437
Accuracy           : 0.9630
Precision          : 0.4666
Recall             : 0.5293
F1 Score           : 0.4960
ROC-AUC            : 0.9056
PR-AUC             : 0.5303
Balanced Accuracy  : 0.7539
MCC                : 0.4779

Confusion Matrix:
[[111585   2459]
 [  1913   2151]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9831    0.9784    0.9808    114044
       Fraud     0.4666    0.5293    0.4960      4064

    accuracy                         0.9630    118108
   macro avg     0.7249    0.7539    0.7384    118108
weighted avg     0.9654    0.9630    0.9641    118108


============================================================
XGBoost - Baseline - SMOTE + Undersampling
============================================================
Features: 437
Accuracy           : 0.9634
Precision          : 0.4719
Recall             : 0.5241
F1 Score           : 0.4966
ROC-AUC            : 0.9046
PR-AUC             : 0.5253
Balanced Accuracy  : 0.7516
MCC                : 0.4784

Confusion Matrix:
[[111660   2384]
 [  1934   2130]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9830    0.9791    0.9810    114044
       Fraud     0.4719    0.5241    0.4966      4064

    accuracy                         0.9634    118108
   macro avg     0.7274    0.7516    0.7388    118108
weighted avg     0.9654    0.9634    0.9644    118108


===== Feature Engineering - Original =====
Train samples: 472,432 | Fraud rate: 0.0351

============================================================
RF - Feature Engineering - Original
============================================================
Features: 439
Accuracy           : 0.9742
Precision          : 0.8149
Recall             : 0.3238
F1 Score           : 0.4635
ROC-AUC            : 0.9074
PR-AUC             : 0.5341
Balanced Accuracy  : 0.6606
MCC                : 0.5041

Confusion Matrix:
[[113745    299]
 [  2748   1316]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9764    0.9974    0.9868    114044
       Fraud     0.8149    0.3238    0.4635      4064

    accuracy                         0.9742    118108
   macro avg     0.8956    0.6606    0.7251    118108
weighted avg     0.9709    0.9742    0.9688    118108


============================================================
LightGBM - Feature Engineering - Original
============================================================
Features: 439
Accuracy           : 0.9017
Precision          : 0.2191
Recall             : 0.7247
F1 Score           : 0.3365
ROC-AUC            : 0.9050
PR-AUC             : 0.5175
Balanced Accuracy  : 0.8163
MCC                : 0.3631

Confusion Matrix:
[[103550  10494]
 [  1119   2945]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9893    0.9080    0.9469    114044
       Fraud     0.2191    0.7247    0.3365      4064

    accuracy                         0.9017    118108
   macro avg     0.6042    0.8163    0.6417    118108
weighted avg     0.9628    0.9017    0.9259    118108


============================================================
XGBoost - Feature Engineering - Original
============================================================
Features: 439
Accuracy           : 0.9126
Precision          : 0.2395
Recall             : 0.7084
F1 Score           : 0.3580
ROC-AUC            : 0.9027
PR-AUC             : 0.5217
Balanced Accuracy  : 0.8141
MCC                : 0.3788

Confusion Matrix:
[[104904   9140]
 [  1185   2879]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9888    0.9199    0.9531    114044
       Fraud     0.2395    0.7084    0.3580      4064

    accuracy                         0.9126    118108
   macro avg     0.6142    0.8141    0.6556    118108
weighted avg     0.9630    0.9126    0.9326    118108


===== Feature Engineering - SMOTE =====
Train samples: 911,666 | Fraud rate: 0.5000

============================================================
RF - Feature Engineering - SMOTE
============================================================
Features: 439
Accuracy           : 0.9742
Precision          : 0.8223
Recall             : 0.3189
F1 Score           : 0.4596
ROC-AUC            : 0.8921
PR-AUC             : 0.5002
Balanced Accuracy  : 0.6582
MCC                : 0.5027

Confusion Matrix:
[[113764    280]
 [  2768   1296]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9762    0.9975    0.9868    114044
       Fraud     0.8223    0.3189    0.4596      4064

    accuracy                         0.9742    118108
   macro avg     0.8993    0.6582    0.7232    118108
weighted avg     0.9710    0.9742    0.9686    118108


============================================================
LightGBM - Feature Engineering - SMOTE
============================================================
Features: 439
Accuracy           : 0.9735
Precision          : 0.7229
Recall             : 0.3735
F1 Score           : 0.4925
ROC-AUC            : 0.8924
PR-AUC             : 0.5141
Balanced Accuracy  : 0.6842
MCC                : 0.5082

Confusion Matrix:
[[113462    582]
 [  2546   1518]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9781    0.9949    0.9864    114044
       Fraud     0.7229    0.3735    0.4925      4064

    accuracy                         0.9735    118108
   macro avg     0.8505    0.6842    0.7395    118108
weighted avg     0.9693    0.9735    0.9694    118108


============================================================
XGBoost - Feature Engineering - SMOTE
============================================================
Features: 439
Accuracy           : 0.9734
Precision          : 0.7355
Recall             : 0.3524
F1 Score           : 0.4765
ROC-AUC            : 0.8937
PR-AUC             : 0.5089
Balanced Accuracy  : 0.6739
MCC                : 0.4980

Confusion Matrix:
[[113529    515]
 [  2632   1432]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9773    0.9955    0.9863    114044
       Fraud     0.7355    0.3524    0.4765      4064

    accuracy                         0.9734    118108
   macro avg     0.8564    0.6739    0.7314    118108
weighted avg     0.9690    0.9734    0.9688    118108


===== Feature Engineering - Undersampling =====
Train samples: 33,198 | Fraud rate: 0.5000

============================================================
RF - Feature Engineering - Undersampling
============================================================
Features: 439
Accuracy           : 0.8701
Precision          : 0.1749
Recall             : 0.7461
F1 Score           : 0.2833
ROC-AUC            : 0.8958
PR-AUC             : 0.4659
Balanced Accuracy  : 0.8103
MCC                : 0.3196

Confusion Matrix:
[[99736 14308]
 [ 1032  3032]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9898    0.8745    0.9286    114044
       Fraud     0.1749    0.7461    0.2833      4064

    accuracy                         0.8701    118108
   macro avg     0.5823    0.8103    0.6060    118108
weighted avg     0.9617    0.8701    0.9064    118108


============================================================
LightGBM - Feature Engineering - Undersampling
============================================================
Features: 439
Accuracy           : 0.8840
Precision          : 0.1961
Recall             : 0.7653
F1 Score           : 0.3122
ROC-AUC            : 0.9092
PR-AUC             : 0.5132
Balanced Accuracy  : 0.8267
MCC                : 0.3494

Confusion Matrix:
[[101295  12749]
 [   954   3110]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9907    0.8882    0.9366    114044
       Fraud     0.1961    0.7653    0.3122      4064

    accuracy                         0.8840    118108
   macro avg     0.5934    0.8267    0.6244    118108
weighted avg     0.9633    0.8840    0.9152    118108


============================================================
XGBoost - Feature Engineering - Undersampling
============================================================
Features: 439
Accuracy           : 0.8850
Precision          : 0.1979
Recall             : 0.7672
F1 Score           : 0.3146
ROC-AUC            : 0.9089
PR-AUC             : 0.5123
Balanced Accuracy  : 0.8282
MCC                : 0.3519

Confusion Matrix:
[[101404  12640]
 [   946   3118]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9908    0.8892    0.9372    114044
       Fraud     0.1979    0.7672    0.3146      4064

    accuracy                         0.8850    118108
   macro avg     0.5943    0.8282    0.6259    118108
weighted avg     0.9635    0.8850    0.9158    118108


===== Feature Engineering - SMOTE + Undersampling =====
Train samples: 248,985 | Fraud rate: 0.3333

============================================================
RF - Feature Engineering - SMOTE + Undersampling
============================================================
Features: 439
Accuracy           : 0.9698
Precision          : 0.5792
Recall             : 0.4429
F1 Score           : 0.5020
ROC-AUC            : 0.8970
PR-AUC             : 0.5091
Balanced Accuracy  : 0.7157
MCC                : 0.4913

Confusion Matrix:
[[112736   1308]
 [  2264   1800]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9803    0.9885    0.9844    114044
       Fraud     0.5792    0.4429    0.5020      4064

    accuracy                         0.9698    118108
   macro avg     0.7797    0.7157    0.7432    118108
weighted avg     0.9665    0.9698    0.9678    118108


============================================================
LightGBM - Feature Engineering - SMOTE + Undersampling
============================================================
Features: 439
Accuracy           : 0.9630
Precision          : 0.4667
Recall             : 0.5226
F1 Score           : 0.4931
ROC-AUC            : 0.9066
PR-AUC             : 0.5270
Balanced Accuracy  : 0.7507
MCC                : 0.4748

Confusion Matrix:
[[111617   2427]
 [  1940   2124]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9829    0.9787    0.9808    114044
       Fraud     0.4667    0.5226    0.4931      4064

    accuracy                         0.9630    118108
   macro avg     0.7248    0.7507    0.7370    118108
weighted avg     0.9652    0.9630    0.9640    118108


============================================================
XGBoost - Feature Engineering - SMOTE + Undersampling
============================================================
Features: 439
Accuracy           : 0.9634
Precision          : 0.4709
Recall             : 0.5244
F1 Score           : 0.4962
ROC-AUC            : 0.9057
PR-AUC             : 0.5288
Balanced Accuracy  : 0.7517
MCC                : 0.4780

Confusion Matrix:
[[111650   2394]
 [  1933   2131]]

Classification Report:
              precision    recall  f1-score   support

  Legitimate     0.9830    0.9790    0.9810    114044
       Fraud     0.4709    0.5244    0.4962      4064

    accuracy                         0.9634    118108
   macro avg     0.7270    0.7517    0.7386    118108
weighted avg     0.9654    0.9634    0.9643    118108

