# ML model results

Reads **all experimental runs** from `saved/ml_results.parquet` (written by `02_ml_models_fit.ipynb`).

Six models × four feature tables:

| Dataset | Features |
|---|---|
| Baseline | original columns, no `uid` / `uid2` / `DT_*` |
| Feature Engineering | plus `uid`, `uid2`, `DT_*` |
| Reduced Baseline | Table 3 filters, no `uid` / `uid2` / `DT_*` |
| Reduced Feature Engineering | reduced plus surviving `uid` / `uid2` / `DT_*` |

Models: logistic regression, decision tree, random forest, LightGBM, XGBoost, CatBoost.

Optuna `BestParams` are used to refit on **all labeled train rows** and score `merged_test.parquet`. Submissions go to `results/{ModelType}_{Dataset}_submission.csv` with columns `TransactionID`, `IsFraud` (fraud probability).

In [1]:
import warnings
import numpy as np
import pandas as pd
import json
import gc
from pathlib import Path
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    confusion_matrix,
    balanced_accuracy_score,
    matthews_corrcoef,
    classification_report,
)
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier

warnings.filterwarnings("ignore")
pd.options.display.precision = 4

print("ML model results")

ML model results

In [2]:
# Environment & Paths Setup

try:
    import google.colab
    IS_COLAB = True
    from google.colab import drive
    drive.mount("/content/drive")
except ImportError:
    IS_COLAB = False

if IS_COLAB:
    ROOT = Path("/content/drive/MyDrive/minor-thesis")
else:
    ROOT = Path.cwd()

DATASET_PATH = ROOT / "dataset"
SAVED_PATH = ROOT / "saved"
RESULTS_DIR = ROOT / "results"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

print(f'Environment: {"Google Colab" if IS_COLAB else "Local"}')
print(f"Dataset path: {DATASET_PATH}")
print(f"Results table: {SAVED_PATH / 'ml_results.parquet'}")
print(f"Submission dir: {RESULTS_DIR}")

Environment: Local
Dataset path: d:\source\RMIT\master-of-ai-new\2026-semester-02\minor-thesis\dataset
Results table: d:\source\RMIT\master-of-ai-new\2026-semester-02\minor-thesis\saved\ml_results.parquet
Submission dir: d:\source\RMIT\master-of-ai-new\2026-semester-02\minor-thesis\results

## Experiment results

One table of every trained run in `saved/ml_results.parquet` (6 models × 4 datasets). Re-run any missing family in `02_ml_models_fit.ipynb`.

In [3]:
from IPython.display import display

ml_results_path = SAVED_PATH / "ml_results.parquet"
all_results = pd.read_parquet(ml_results_path)
all_results = all_results[
    ~all_results["Model"].astype(str).str.startswith(("SVM -", "KNN -"))
]

MODEL_ORDER = [
    "LogisticRegression",
    "DecisionTree",
    "RandomForest",
    "LightGBM",
    "XGBoost",
    "CatBoost",
]
DATASET_ORDER = [
    "Baseline",
    "Feature Engineering",
    "Reduced Baseline",
    "Reduced Feature Engineering",
]
NAME_PREFIX = {
    "LogisticRegression": "Logistic Regression",
    "DecisionTree": "Decision Tree",
    "RandomForest": "RF",
    "LightGBM": "LightGBM",
    "XGBoost": "XGBoost",
    "CatBoost": "CatBoost",
}

if "Dataset" not in all_results.columns:
    all_results["Dataset"] = all_results["Model"].astype(str).str.split(" - ", n=1).str[1]

expected = {
    f"{prefix} - {dataset}"
    for prefix in NAME_PREFIX.values()
    for dataset in DATASET_ORDER
}
missing = sorted(expected - set(all_results["Model"].astype(str)))

show_cols = [
    "ModelType",
    "Dataset",
    "Features",
    "Accuracy",
    "Precision",
    "Recall",
    "F1",
    "ROC-AUC",
    "TuneROC-AUC",
    "PR-AUC",
    "Balanced Accuracy",
    "MCC",
    "TP",
    "FP",
    "FN",
    "TN",
    "BestParams",
]
show_cols = [c for c in show_cols if c in all_results.columns]

results_table = all_results.copy()
results_table["ModelType"] = pd.Categorical(
    results_table["ModelType"], categories=MODEL_ORDER, ordered=True
)
results_table["Dataset"] = pd.Categorical(
    results_table["Dataset"], categories=DATASET_ORDER, ordered=True
)
results_table = (
    results_table.sort_values(["ModelType", "Dataset"])[show_cols].reset_index(drop=True)
)

print(
    f"{ml_results_path.name}: {len(results_table)} trained runs "
    f"(expected 24 = 6 models x 4 datasets)"
)
if missing:
    print("Not trained yet:")
    for name in missing:
        print(f"  {name}")
print()
display(results_table)

ml_results.parquet: 24 trained runs (expected 24 = 6 models x 4 datasets)

,ModelType,Dataset,Features,Accuracy,Precision,Recall,F1,ROC-AUC,TuneROC-AUC,PR-AUC,Balanced Accuracy,MCC,TP,FP,FN,TN,BestParams
0,LogisticRegression,Baseline,432,0.7058,0.0878,0.8039,0.1583,0.8335,0.8538,0.2067,0.7531,0.1986,3267,33946,797,80098,"{""C"": 1.9942666309136752}"
1,LogisticRegression,Feature Engineering,439,0.7091,0.0885,0.8022,0.1595,0.8334,0.8517,0.2094,0.7540,0.1999,3260,33556,804,80488,"{""C"": 6.051195987836167}"
2,LogisticRegression,Reduced Baseline,342,0.6881,0.0834,0.8076,0.1513,0.8248,0.8486,0.1771,0.7457,0.1901,3282,36051,782,77993,"{""C"": 9.177237615941623}"
3,LogisticRegression,Reduced Feature Engineering,348,0.6976,0.0850,0.7975,0.1536,0.8248,0.8462,0.1802,0.7457,0.1916,3241,34897,823,79147,"{""C"": 2.9154431891537547}"
4,DecisionTree,Baseline,432,0.8150,0.1167,0.6663,0.1986,0.8251,0.8385,0.3310,0.7433,0.2233,2708,20493,1356,93551,"{""max_depth"": 8, ""min_samples_leaf"": 43, ""min_..."
5,DecisionTree,Feature Engineering,439,0.8181,0.1198,0.6754,0.2035,0.7965,0.8451,0.3368,0.7493,0.2298,2745,20170,1319,93874,"{""max_depth"": 13, ""min_samples_leaf"": 49, ""min..."
6,DecisionTree,Reduced Baseline,342,0.8237,0.1210,0.6580,0.2044,0.8221,0.8362,0.3320,0.7438,0.2279,2674,19428,1390,94616,"{""max_depth"": 9, ""min_samples_leaf"": 64, ""min_..."
7,DecisionTree,Reduced Feature Engineering,348,0.8306,0.1303,0.6912,0.2193,0.8307,0.8482,0.3506,0.7634,0.2486,2809,18750,1255,95294,"{""max_depth"": 8, ""min_samples_leaf"": 26, ""min_..."
8,RandomForest,Baseline,432,0.9295,0.2690,0.6097,0.3733,0.8959,0.9008,0.4875,0.7753,0.3743,2478,6735,1586,107309,"{""n_estimators"": 250, ""max_depth"": 25, ""min_sa..."
9,RandomForest,Feature Engineering,439,0.9305,0.2710,0.6031,0.3740,0.8961,0.9001,0.4885,0.7726,0.3738,2451,6592,1613,107452,"{""n_estimators"": 250, ""max_depth"": 25, ""min_sa..."
10,RandomForest,Reduced Baseline,342,0.9406,0.3046,0.5669,0.3963,0.8907,0.8986,0.4858,0.7604,0.3877,2304,5261,1760,108783,"{""n_estimators"": 250, ""max_depth"": 23, ""min_sa..."
11,RandomForest,Reduced Feature Engineering,348,0.9455,0.3271,0.5527,0.4110,0.8922,0.9007,0.4894,0.7561,0.3990,2246,4620,1818,109424,"{""n_estimators"": 400, ""max_depth"": 23, ""min_sa..."
12,LightGBM,Baseline,432,0.9421,0.3286,0.6533,0.4373,0.9109,0.9239,0.5498,0.8029,0.4374,2655,5424,1409,108620,"{""n_estimators"": 700, ""learning_rate"": 0.03702..."
13,LightGBM,Feature Engineering,439,0.9455,0.3467,0.6587,0.4543,0.9163,0.9251,0.5593,0.8072,0.4531,2677,5045,1387,108999,"{""n_estimators"": 700, ""learning_rate"": 0.03702..."
14,LightGBM,Reduced Baseline,342,0.9642,0.4822,0.5672,0.5213,0.9118,0.9235,0.5550,0.7727,0.5045,2305,2475,1759,111569,"{""n_estimators"": 800, ""learning_rate"": 0.05839..."
15,LightGBM,Reduced Feature Engineering,348,0.9283,0.2787,0.6826,0.3958,0.9129,0.9259,0.5381,0.8098,0.4066,2774,7179,1290,106865,"{""n_estimators"": 500, ""learning_rate"": 0.04003..."
16,XGBoost,Baseline,432,0.9647,0.4887,0.5706,0.5265,0.9114,0.9230,0.5624,0.7747,0.5099,2319,2426,1745,111618,"{""n_estimators"": 500, ""learning_rate"": 0.05156..."
17,XGBoost,Feature Engineering,439,0.9749,0.6805,0.5074,0.5813,0.9196,0.9247,0.5965,0.7494,0.5752,2062,968,2002,113076,"{""n_estimators"": 700, ""learning_rate"": 0.07627..."
18,XGBoost,Reduced Baseline,342,0.9653,0.4959,0.5605,0.5262,0.9120,0.9209,0.5604,0.7701,0.5093,2278,2316,1786,111728,"{""n_estimators"": 500, ""learning_rate"": 0.05156..."
19,XGBoost,Reduced Feature Engineering,348,0.9704,0.5761,0.5327,0.5536,0.9163,0.9227,0.5717,0.7594,0.5387,2165,1593,1899,112451,"{""n_estimators"": 600, ""learning_rate"": 0.05367..."
20,CatBoost,Baseline,432,0.9025,0.2228,0.7362,0.3420,0.9078,0.9160,0.5156,0.8223,0.3701,2992,10440,1072,103604,"{""iterations"": 800, ""learning_rate"": 0.0537691..."
21,CatBoost,Feature Engineering,439,0.8987,0.2149,0.7323,0.3323,0.9087,0.9190,0.5065,0.8185,0.3609,2976,10871,1088,103173,"{""iterations"": 800, ""learning_rate"": 0.0328339..."
22,CatBoost,Reduced Baseline,342,0.9099,0.2356,0.7205,0.3551,0.9093,0.9155,0.5119,0.8186,0.3785,2928,9500,1136,104544,"{""iterations"": 700, ""learning_rate"": 0.0832296..."
23,CatBoost,Reduced Feature Engineering,348,0.9034,0.2227,0.7261,0.3409,0.9095,0.9182,0.5094,0.8179,0.3673,2951,10298,1113,103746,"{""iterations"": 650, ""learning_rate"": 0.0495505..."

## Top 20 feature importances

Each training run stores its top 20 features (with `%` of total model importance) in `Top20Importances`. Re-run those experiments in `02_ml_models_fit.ipynb` if the column is missing.

In [4]:
def parse_top20(value):
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return None
    if isinstance(value, str):
        text = value.strip()
        if not text:
            return None
        return pd.DataFrame(json.loads(text))
    if isinstance(value, (list, tuple)):
        return pd.DataFrame(value)
    return None


def show_top20(model_name):
    rows = all_results[all_results["Model"] == model_name]
    if rows.empty:
        print(f"{model_name}: not in ml_results.parquet")
        return
    row = rows.iloc[0]
    if "Top20Importances" not in all_results.columns:
        print("Top20Importances column missing — re-run 02_ml_models.ipynb")
        return
    table = parse_top20(row["Top20Importances"])
    if table is None or table.empty:
        print(f"{model_name}: no top-20 saved yet — re-run that experiment in 02_ml_models.ipynb")
        return
    table = table.rename(
        columns={
            "rank": "Rank",
            "feature": "Feature",
            "importance": "Importance",
            "importance_pct": "Importance %",
        }
    )
    print(
        f"\n{model_name}  |  {int(row['Features'])} features  |  "
        f"ROC-AUC {row['ROC-AUC']:.4f}  |  F1 {row['F1']:.4f}"
    )
    display(table)


if "Top20Importances" not in all_results.columns:
    print("Top20Importances is not in ml_results.parquet yet.")
    print("Re-run the experiment cells in 02_ml_models.ipynb, then re-load this notebook.")
else:
    n_saved = all_results["Top20Importances"].notna().sum()
    print(f"Runs with top-20 importances: {n_saved} / {len(all_results)}")

    highlight = [
        "Logistic Regression - Baseline",
        "Decision Tree - Baseline",
        "RF - Baseline",
        "LightGBM - Baseline",
        "XGBoost - Baseline",
        "CatBoost - Baseline",
        "RF - Feature Engineering",
        "LightGBM - Feature Engineering",
        "XGBoost - Feature Engineering",
        "CatBoost - Feature Engineering",
        "RF - Reduced Baseline",
        "LightGBM - Reduced Baseline",
        "XGBoost - Reduced Baseline",
        "CatBoost - Reduced Baseline",
        "RF - Reduced Feature Engineering",
        "LightGBM - Reduced Feature Engineering",
        "XGBoost - Reduced Feature Engineering",
        "CatBoost - Reduced Feature Engineering",
    ]
    for name in highlight:
        show_top20(name)

    print("\n===== BEST ROC-AUC PER MODEL FAMILY =====")
    for family in MODEL_ORDER:
        frame = all_results[all_results["ModelType"] == family]
        if frame.empty:
            continue
        best_name = frame.sort_values("ROC-AUC", ascending=False).iloc[0]["Model"]
        print(f"\n{family} best: {best_name}")
        show_top20(best_name)

Runs with top-20 importances: 24 / 24

Logistic Regression - Baseline  |  432 features  |  ROC-AUC 0.8335  |  F1 0.1583

    Rank Feature  Importance  Importance %
0      1     C11      9.4344        1.7884
1      2    V283      8.4487        1.6015
2      3     C14      8.1261        1.5404
3      4    V300      7.6893        1.4576
4      5    V218      7.1620        1.3576
5      6    V258      6.8203        1.2928
6      7     V87      6.7427        1.2781
7      8     V45      6.6559        1.2617
8      9     C12      6.3649        1.2065
9     10    V123      6.0615        1.1490
10    11    V201      5.6046        1.0624
11    12    V229      5.1192        0.9704
12    13    V257      4.6403        0.8796
13    14    V200      4.6040        0.8727
14    15    V187      4.5728        0.8668
15    16    V223      4.4176        0.8374
16    17     V44      4.3909        0.8323
17    18    V199      4.2570        0.8069
18    19    V115      4.2189        0.7997
19    20    V241      4.0711        0.7717

Decision Tree - Baseline  |  432 features  |  ROC-AUC 0.8251  |  F1 0.1986

    Rank         Feature  Importance  Importance %
0      1            V218      0.3303       33.0275
1      2            V102      0.1359       13.5950
2      3              C8      0.1086       10.8614
3      4           card6      0.0621        6.2078
4      5             V29      0.0462        4.6187
5      6            V334      0.0315        3.1525
6      7            V306      0.0287        2.8709
7      8             V69      0.0263        2.6262
8      9            V190      0.0214        2.1443
9     10             C14      0.0175        1.7547
10    11             C11      0.0120        1.1956
11    12            V288      0.0107        1.0724
12    13            V281      0.0094        0.9359
13    14  TransactionAmt      0.0090        0.8969
14    15            V280      0.0082        0.8242
15    16            V308      0.0067        0.6691
16    17              C2      0.0065        0.6453
17    18             V47      0.0058        0.5810
18    19             V49      0.0054        0.5381
19    20            V168      0.0048        0.4755

RF - Baseline: no top-20 saved yet — re-run that experiment in 02_ml_models.ipynb

LightGBM - Baseline  |  432 features  |  ROC-AUC 0.9109  |  F1 0.4373

    Rank         Feature  Importance  Importance %
0      1           card1      3833.0        5.8876
1      2   TransactionDT      3436.0        5.2778
2      3  TransactionAmt      3068.0        4.7125
3      4           card2      3052.0        4.6880
4      5           addr1      2668.0        4.0981
5      6             C13      1763.0        2.7080
6      7             D15      1524.0        2.3409
7      8   P_emaildomain      1391.0        2.1366
8      9             D10      1231.0        1.8908
9     10              D1      1192.0        1.8309
10    11           dist1      1186.0        1.8217
11    12              D2      1169.0        1.7956
12    13           card5      1139.0        1.7495
13    14              D4      1078.0        1.6558
14    15              C1       939.0        1.4423
15    16              C2       844.0        1.2964
16    17             C14       803.0        1.2334
17    18           id_02       753.0        1.1566
18    19           id_20       712.0        1.0937
19    20             D11       707.0        1.0860

XGBoost - Baseline  |  432 features  |  ROC-AUC 0.9114  |  F1 0.5265

    Rank Feature  Importance  Importance %
0      1    V258      0.1362       13.6173
1      2     V70      0.0763        7.6341
2      3    V257      0.0585        5.8501
3      4    V218      0.0559        5.5941
4      5     V91      0.0340        3.3973
5      6    V294      0.0276        2.7643
6      7    V322      0.0131        1.3076
7      8      C8      0.0114        1.1401
8      9    V201      0.0100        0.9954
9     10    V264      0.0091        0.9121
10    11    V187      0.0087        0.8717
11    12     C14      0.0079        0.7931
12    13    V283      0.0075        0.7514
13    14    V317      0.0075        0.7475
14    15     V90      0.0064        0.6400
15    16    V138      0.0058        0.5803
16    17      C4      0.0057        0.5730
17    18    V318      0.0054        0.5389
18    19     V69      0.0052        0.5176
19    20   addr2      0.0050        0.5036

CatBoost - Baseline  |  432 features  |  ROC-AUC 0.9078  |  F1 0.3420

    Rank         Feature  Importance  Importance %
0      1           card2      4.9716        4.9716
1      2              C1      4.6106        4.6106
2      3             C13      4.4285        4.4285
3      4           card1      4.0856        4.0856
4      5           addr1      3.6448        3.6448
5      6             C14      3.3289        3.3289
6      7  TransactionAmt      3.0649        3.0649
7      8              D2      2.9372        2.9372
8      9   TransactionDT      2.6426        2.6426
9     10             C11      2.3589        2.3589
10    11              C2      2.2936        2.2936
11    12   P_emaildomain      1.9419        1.9419
12    13             D15      1.9364        1.9364
13    14           card6      1.8318        1.8318
14    15              C6      1.6677        1.6677
15    16              D1      1.6253        1.6253
16    17           card5      1.5892        1.5892
17    18              M6      1.5395        1.5395
18    19   R_emaildomain      1.4306        1.4306
19    20              M4      1.4264        1.4264

RF - Feature Engineering: no top-20 saved yet — re-run that experiment in 02_ml_models.ipynb

LightGBM - Feature Engineering  |  439 features  |  ROC-AUC 0.9163  |  F1 0.4543

    Rank         Feature  Importance  Importance %
0      1           card1      2968.0        4.5420
1      2   TransactionDT      2827.0        4.3262
2      3  TransactionAmt      2792.0        4.2726
3      4           card2      2606.0        3.9880
4      5             uid      2466.0        3.7738
5      6           addr1      2408.0        3.6850
6      7            uid2      1752.0        2.6811
7      8             C13      1472.0        2.2526
8      9             D15      1359.0        2.0797
9     10          DT_day      1353.0        2.0705
10    11   P_emaildomain      1292.0        1.9772
11    12             D10      1097.0        1.6788
12    13              D1      1078.0        1.6497
13    14              D2      1069.0        1.6359
14    15           dist1      1061.0        1.6237
15    16         DT_hour      1053.0        1.6114
16    17           card5      1048.0        1.6038
17    18              D4       938.0        1.4354
18    19              C1       910.0        1.3926
19    20           id_02       731.0        1.1187

XGBoost - Feature Engineering  |  439 features  |  ROC-AUC 0.9196  |  F1 0.5813

    Rank Feature  Importance  Importance %
0      1    V258      0.2107       21.0716
1      2    V257      0.0661        6.6074
2      3     V70      0.0601        6.0129
3      4     V91      0.0363        3.6341
4      5    V294      0.0363        3.6289
5      6    V201      0.0106        1.0583
6      7    V187      0.0082        0.8200
7      8     C14      0.0079        0.7881
8      9      C8      0.0078        0.7767
9     10    V264      0.0077        0.7727
10    11    V336      0.0074        0.7400
11    12    V283      0.0066        0.6575
12    13      C4      0.0065        0.6530
13    14    V162      0.0064        0.6391
14    15    V322      0.0062        0.6207
15    16    V138      0.0059        0.5875
16    17   addr2      0.0056        0.5618
17    18    V121      0.0053        0.5304
18    19    V197      0.0052        0.5177
19    20    V161      0.0042        0.4194

CatBoost - Feature Engineering  |  439 features  |  ROC-AUC 0.9087  |  F1 0.3323

    Rank         Feature  Importance  Importance %
0      1              C1      5.1258        5.1258
1      2           card2      4.5782        4.5782
2      3             C13      4.2734        4.2734
3      4             uid      3.4408        3.4408
4      5           card1      3.1238        3.1238
5      6             C14      3.1219        3.1219
6      7           addr1      2.9855        2.9855
7      8  TransactionAmt      2.8438        2.8438
8      9              D2      2.4523        2.4523
9     10              C2      2.4416        2.4416
10    11           card6      2.0171        2.0171
11    12   P_emaildomain      2.0062        2.0062
12    13             D15      1.9662        1.9662
13    14             C11      1.8630        1.8630
14    15              C6      1.7484        1.7484
15    16   TransactionDT      1.7328        1.7328
16    17            uid2      1.6718        1.6718
17    18              D1      1.5920        1.5920
18    19              M6      1.5867        1.5867
19    20           card5      1.5484        1.5484

RF - Reduced Baseline: no top-20 saved yet — re-run that experiment in 02_ml_models.ipynb

LightGBM - Reduced Baseline  |  342 features  |  ROC-AUC 0.9118  |  F1 0.5213

    Rank         Feature  Importance  Importance %
0      1           card1      5426.0        7.1454
1      2   TransactionDT      5162.0        6.7977
2      3  TransactionAmt      4376.0        5.7627
3      4           card2      4080.0        5.3729
4      5           addr1      3959.0        5.2135
5      6             C13      1834.0        2.4152
6      7   P_emaildomain      1818.0        2.3941
7      8             D15      1816.0        2.3915
8      9           dist1      1722.0        2.2677
9     10           card5      1569.0        2.0662
10    11             D10      1405.0        1.8502
11    12              C1      1325.0        1.7449
12    13              D2      1257.0        1.6553
13    14              D1      1219.0        1.6053
14    15              D4      1218.0        1.6040
15    16           id_02      1060.0        1.3959
16    17           id_20       936.0        1.2326
17    18           id_19       879.0        1.1575
18    19      DeviceInfo       858.0        1.1299
19    20             D11       848.0        1.1167

XGBoost - Reduced Baseline  |  342 features  |  ROC-AUC 0.9120  |  F1 0.5262

    Rank Feature  Importance  Importance %
0      1    V258      0.1594       15.9378
1      2     V70      0.0822        8.2236
2      3    V218      0.0732        7.3202
3      4    V257      0.0697        6.9679
4      5     V91      0.0334        3.3442
5      6    V201      0.0248        2.4803
6      7    V317      0.0218        2.1760
7      8      C4      0.0127        1.2667
8      9    V187      0.0081        0.8133
9     10    V264      0.0076        0.7650
10    11    V295      0.0075        0.7456
11    12     C14      0.0074        0.7354
12    13    V283      0.0068        0.6791
13    14   addr2      0.0062        0.6199
14    15    V323      0.0056        0.5573
15    16    V312      0.0051        0.5121
16    17   card6      0.0050        0.5048
17    18    V156      0.0048        0.4799
18    19    V318      0.0045        0.4528
19    20    V197      0.0044        0.4431

CatBoost - Reduced Baseline  |  342 features  |  ROC-AUC 0.9093  |  F1 0.3551

    Rank         Feature  Importance  Importance %
0      1              C1      8.6692        8.6692
1      2           card2      4.7515        4.7515
2      3           card1      4.6733        4.6733
3      4             C14      4.0190        4.0190
4      5           addr1      3.7987        3.7987
5      6             C13      3.7739        3.7739
6      7  TransactionAmt      3.3275        3.3275
7      8   TransactionDT      3.0397        3.0397
8      9   P_emaildomain      2.3610        2.3610
9     10              D2      2.2361        2.2361
10    11             D15      1.9853        1.9853
11    12           card6      1.9650        1.9650
12    13              D1      1.9232        1.9232
13    14              C5      1.7980        1.7980
14    15   R_emaildomain      1.5390        1.5390
15    16             D10      1.5278        1.5278
16    17              M5      1.4001        1.4001
17    18           card5      1.3842        1.3842
18    19              C4      1.3792        1.3792
19    20            V258      1.3658        1.3658

RF - Reduced Feature Engineering: no top-20 saved yet — re-run that experiment in 02_ml_models.ipynb

LightGBM - Reduced Feature Engineering  |  348 features  |  ROC-AUC 0.9129  |  F1 0.3958

    Rank         Feature  Importance  Importance %
0      1   TransactionDT      1850.0        4.5764
1      2  TransactionAmt      1844.0        4.5615
2      3           card1      1827.0        4.5195
3      4           card2      1766.0        4.3686
4      5             uid      1629.0        4.0297
5      6           addr1      1532.0        3.7897
6      7            uid2      1111.0        2.7483
7      8             C13      1069.0        2.6444
8      9             D15       972.0        2.4045
9     10              C1       889.0        2.1991
10    11   P_emaildomain       865.0        2.1398
11    12              D2       803.0        1.9864
12    13             D10       797.0        1.9716
13    14              D1       771.0        1.9072
14    15           dist1       738.0        1.8256
15    16           card5       701.0        1.7341
16    17              D4       637.0        1.5758
17    18         DT_hour       605.0        1.4966
18    19             C14       542.0        1.3408
19    20             D11       451.0        1.1156

XGBoost - Reduced Feature Engineering  |  348 features  |  ROC-AUC 0.9163  |  F1 0.5536

    Rank    Feature  Importance  Importance %
0      1       V258      0.1949       19.4875
1      2        V70      0.0672        6.7246
2      3       V257      0.0651        6.5083
3      4       V218      0.0599        5.9904
4      5        V91      0.0423        4.2339
5      6       V317      0.0207        2.0726
6      7       V201      0.0161        1.6114
7      8         C4      0.0117        1.1741
8      9       V187      0.0094        0.9366
9     10       V264      0.0081        0.8100
10    11        C14      0.0077        0.7747
11    12       V323      0.0065        0.6470
12    13       V283      0.0064        0.6406
13    14      addr2      0.0059        0.5909
14    15       V312      0.0048        0.4803
15    16       V156      0.0047        0.4678
16    17       V295      0.0046        0.4618
17    18      card6      0.0044        0.4423
18    19       V122      0.0044        0.4380
19    20  ProductCD      0.0042        0.4214

CatBoost - Reduced Feature Engineering  |  348 features  |  ROC-AUC 0.9095  |  F1 0.3409

    Rank         Feature  Importance  Importance %
0      1              C1      8.4052        8.4052
1      2           card2      4.5254        4.5254
2      3             C13      3.5556        3.5556
3      4           addr1      3.5401        3.5401
4      5             C14      3.4880        3.4880
5      6  TransactionAmt      3.2069        3.2069
6      7             uid      3.1911        3.1911
7      8           card1      2.9155        2.9155
8      9              D2      2.8081        2.8081
9     10   P_emaildomain      2.3440        2.3440
10    11             D15      2.2607        2.2607
11    12           card5      2.0542        2.0542
12    13           card6      2.0328        2.0328
13    14   TransactionDT      1.9692        1.9692
14    15              M5      1.8142        1.8142
15    16            uid2      1.6942        1.6942
16    17             D10      1.6613        1.6613
17    18              M6      1.5582        1.5582
18    19              C9      1.5243        1.5243
19    20              D1      1.3387        1.3387

===== BEST ROC-AUC PER MODEL FAMILY =====

LogisticRegression best: Logistic Regression - Baseline

Logistic Regression - Baseline  |  432 features  |  ROC-AUC 0.8335  |  F1 0.1583

    Rank Feature  Importance  Importance %
0      1     C11      9.4344        1.7884
1      2    V283      8.4487        1.6015
2      3     C14      8.1261        1.5404
3      4    V300      7.6893        1.4576
4      5    V218      7.1620        1.3576
5      6    V258      6.8203        1.2928
6      7     V87      6.7427        1.2781
7      8     V45      6.6559        1.2617
8      9     C12      6.3649        1.2065
9     10    V123      6.0615        1.1490
10    11    V201      5.6046        1.0624
11    12    V229      5.1192        0.9704
12    13    V257      4.6403        0.8796
13    14    V200      4.6040        0.8727
14    15    V187      4.5728        0.8668
15    16    V223      4.4176        0.8374
16    17     V44      4.3909        0.8323
17    18    V199      4.2570        0.8069
18    19    V115      4.2189        0.7997
19    20    V241      4.0711        0.7717

DecisionTree best: Decision Tree - Reduced Feature Engineering

Decision Tree - Reduced Feature Engineering  |  348 features  |  ROC-AUC 0.8307  |  F1 0.2193

    Rank         Feature  Importance  Importance %
0      1            V258      0.2876       28.7585
1      2            V317      0.1722       17.2157
2      3             C14      0.1291       12.9141
3      4              C4      0.0849        8.4876
4      5              M4      0.0468        4.6763
5      6           card6      0.0382        3.8174
6      7              C1      0.0353        3.5332
7      8   TransactionDT      0.0173        1.7331
8      9  TransactionAmt      0.0170        1.6970
9     10            V306      0.0161        1.6118
10    11             V91      0.0117        1.1740
11    12             C13      0.0108        1.0762
12    13            V283      0.0102        1.0242
13    14            V210      0.0095        0.9463
14    15             D15      0.0087        0.8705
15    16            V309      0.0082        0.8223
16    17              D1      0.0061        0.6102
17    18              C5      0.0059        0.5885
18    19             V53      0.0051        0.5109
19    20            V310      0.0049        0.4866

RandomForest best: RF - Feature Engineering
RF - Feature Engineering: no top-20 saved yet — re-run that experiment in 02_ml_models.ipynb

LightGBM best: LightGBM - Feature Engineering

LightGBM - Feature Engineering  |  439 features  |  ROC-AUC 0.9163  |  F1 0.4543

    Rank         Feature  Importance  Importance %
0      1           card1      2968.0        4.5420
1      2   TransactionDT      2827.0        4.3262
2      3  TransactionAmt      2792.0        4.2726
3      4           card2      2606.0        3.9880
4      5             uid      2466.0        3.7738
5      6           addr1      2408.0        3.6850
6      7            uid2      1752.0        2.6811
7      8             C13      1472.0        2.2526
8      9             D15      1359.0        2.0797
9     10          DT_day      1353.0        2.0705
10    11   P_emaildomain      1292.0        1.9772
11    12             D10      1097.0        1.6788
12    13              D1      1078.0        1.6497
13    14              D2      1069.0        1.6359
14    15           dist1      1061.0        1.6237
15    16         DT_hour      1053.0        1.6114
16    17           card5      1048.0        1.6038
17    18              D4       938.0        1.4354
18    19              C1       910.0        1.3926
19    20           id_02       731.0        1.1187

XGBoost best: XGBoost - Feature Engineering

XGBoost - Feature Engineering  |  439 features  |  ROC-AUC 0.9196  |  F1 0.5813

    Rank Feature  Importance  Importance %
0      1    V258      0.2107       21.0716
1      2    V257      0.0661        6.6074
2      3     V70      0.0601        6.0129
3      4     V91      0.0363        3.6341
4      5    V294      0.0363        3.6289
5      6    V201      0.0106        1.0583
6      7    V187      0.0082        0.8200
7      8     C14      0.0079        0.7881
8      9      C8      0.0078        0.7767
9     10    V264      0.0077        0.7727
10    11    V336      0.0074        0.7400
11    12    V283      0.0066        0.6575
12    13      C4      0.0065        0.6530
13    14    V162      0.0064        0.6391
14    15    V322      0.0062        0.6207
15    16    V138      0.0059        0.5875
16    17   addr2      0.0056        0.5618
17    18    V121      0.0053        0.5304
18    19    V197      0.0052        0.5177
19    20    V161      0.0042        0.4194

CatBoost best: CatBoost - Reduced Feature Engineering

CatBoost - Reduced Feature Engineering  |  348 features  |  ROC-AUC 0.9095  |  F1 0.3409

    Rank         Feature  Importance  Importance %
0      1              C1      8.4052        8.4052
1      2           card2      4.5254        4.5254
2      3             C13      3.5556        3.5556
3      4           addr1      3.5401        3.5401
4      5             C14      3.4880        3.4880
5      6  TransactionAmt      3.2069        3.2069
6      7             uid      3.1911        3.1911
7      8           card1      2.9155        2.9155
8      9              D2      2.8081        2.8081
9     10   P_emaildomain      2.3440        2.3440
10    11             D15      2.2607        2.2607
11    12           card5      2.0542        2.0542
12    13           card6      2.0328        2.0328
13    14   TransactionDT      1.9692        1.9692
14    15              M5      1.8142        1.8142
15    16            uid2      1.6942        1.6942
16    17             D10      1.6613        1.6613
17    18              M6      1.5582        1.5582
18    19              C9      1.5243        1.5243
19    20              D1      1.3387        1.3387

## Imbalanced-data read

Accuracy is misleading at a 3.5% fraud rate. Rank the four-dataset runs by ROC-AUC, PR-AUC, F1, and recall.

In [5]:
print("=" * 130)
print("IMBALANCED DATASET ANALYSIS - FOR FRAUD DETECTION")
print("Focus: ROC-AUC, PR-AUC, F1, Recall (NOT Accuracy - accuracy is misleading!)")
print("=" * 130)

print("\n1. KEY METRICS FOR IMBALANCED DATA")
print("-" * 130)
print("""
For fraud detection (imbalanced dataset):

ROC-AUC (0.85-0.95 good)
  - Threshold-independent, handles class imbalance naturally
  - Main metric for comparing models

PR-AUC (Precision-Recall)
  - Especially important when fraud is rare
  - Shows trade-off: catch more frauds vs avoid false alerts

F1 Score
  - Harmonic mean of Precision & Recall
  - Balances both metrics

Recall (Sensitivity)
  - % of actual frauds caught
  - Missing a fraud = business loss

Precision
  - % of fraud alerts that are actually fraud
  - False alert = customer friction

Confusion Matrix (TN, FP, FN, TP)
  - FN (False Negatives) = frauds we missed - WORST outcome
  - FP (False Positives) = customers falsely flagged - customer friction
  - TP (True Positives) = frauds caught - GOOD
  - TN (True Negatives) = legitimate txns correctly allowed - GOOD

Accuracy - MISLEADING for imbalanced data!
  Example: 99% legitimates, 1% fraud
  Model that predicts "always legitimate" = 99% accuracy but CATCHES ZERO FRAUDS
""")

print("\n\n2. TOP CANDIDATES FOR IMBALANCED FRAUD DETECTION (ROC-AUC > 0.90)")
print("-" * 130)

high_roc = all_results[all_results["ROC-AUC"] > 0.90].sort_values(
    ["Features", "ROC-AUC"], ascending=[True, False]
)
display_cols = ["Model", "Features", "ROC-AUC", "PR-AUC", "F1", "Recall", "Precision", "TP", "FP", "FN"]
print(high_roc[display_cols].head(15).to_string(index=False))

print("\n\n3. DETAILED COMPARISON - THREE MAIN CANDIDATES")
print("=" * 130)

focus = [
    "RF - Baseline",
    "RF - Feature Engineering",
    "RF - Reduced Baseline",
    "RF - Reduced Feature Engineering",
    "LightGBM - Reduced Feature Engineering",
    "XGBoost - Reduced Feature Engineering",
    "CatBoost - Reduced Feature Engineering",
]

for model_name in focus:
    row = all_results[all_results["Model"] == model_name]
    if len(row) == 0:
        continue
    row = row.iloc[0]

    print(f"\n{model_name}")
    print("-" * 130)

    print("\nCore Metrics (for imbalanced data):")
    print(f"  ROC-AUC:              {row['ROC-AUC']:.4f}  <- Main comparison metric")
    print(f"  PR-AUC:               {row['PR-AUC']:.4f}  <- Critical for fraud (rare events)")
    print(f"  F1 Score:             {row['F1']:.4f}   <- Balance precision & recall")

    print("\nFraud Detection Performance:")
    print(f"  Recall (catch rate):  {row['Recall']:.4f}   <- % of frauds actually caught")
    print(f"  Precision:            {row['Precision']:.4f}  <- % of alerts that are real frauds")

    print("\nConfusion Matrix Breakdown:")
    tn, fp, fn, tp = int(row["TN"]), int(row["FP"]), int(row["FN"]), int(row["TP"])
    total = tn + fp + fn + tp
    specificity = tn / (tn + fp) if (tn + fp) > 0 else 0
    sensitivity = tp / (tp + fn) if (tp + fn) > 0 else 0

    print(f"  True Negatives (TN):   {tn:8d}  <- Legitimate txns correctly allowed")
    print(f"  False Positives (FP):  {fp:8d}  <- Legitimate txns falsely flagged (customer friction)")
    print(f"  False Negatives (FN):  {fn:8d}  <- Frauds missed (WORST - direct loss!)")
    print(f"  True Positives (TP):   {tp:8d}  <- Frauds caught (BEST)")
    print("  -----------------------------------")
    print(f"  Total samples:         {total:8d}")

    print("\nDerived Metrics:")
    print(f"  Specificity:          {specificity:.4f}   <- % of legitimate txns correctly allowed")
    print(f"  Sensitivity:          {sensitivity:.4f}   <- % of frauds caught (same as Recall)")
    print(f"  False Alarm Rate:     {fp / (fp + tn):.4f}   <- % of legitimate txns falsely flagged")
    print(f"  False Negative Rate:  {fn / (fn + tp):.4f}   <- % of frauds missed (minimize this!)")

    print(f"  Features:             {int(row['Features'])} columns")

print("\n\n4. RECOMMENDATION FOR IMBALANCED FRAUD DETECTION")
print("=" * 130)
print("""
KEY INSIGHT FOR IMBALANCED DATA:

Priority:
1. MINIMIZE FN (False Negatives / Missed Frauds) <- Direct business loss
2. MAINTAIN ROC-AUC > 0.90 <- Threshold-independent quality
3. MAXIMIZE F1 & Recall <- Better fraud detection
4. MANAGE FP (False Positives) <- Customer experience
5. IGNORE Accuracy <- Misleading for imbalanced data

BEST CHOICE: re-run 02_ml_models_fit.ipynb, then pick the row with highest PR-AUC / F1 among the four tables.

Compare Baseline vs Feature Engineering vs Reduced Baseline vs Reduced Feature Engineering
for each model family. Group-ablation permutations (Remove C / D / M / id / V) are no longer trained.
""")
print("=" * 130)

==================================================================================================================================
IMBALANCED DATASET ANALYSIS - FOR FRAUD DETECTION
Focus: ROC-AUC, PR-AUC, F1, Recall (NOT Accuracy - accuracy is misleading!)
==================================================================================================================================

1. KEY METRICS FOR IMBALANCED DATA
----------------------------------------------------------------------------------------------------------------------------------

For fraud detection (imbalanced dataset):

ROC-AUC (0.85-0.95 good)
  - Threshold-independent, handles class imbalance naturally
  - Main metric for comparing models

PR-AUC (Precision-Recall)
  - Especially important when fraud is rare
  - Shows trade-off: catch more frauds vs avoid false alerts

F1 Score
  - Harmonic mean of Precision & Recall
  - Balances both metrics

Recall (Sensitivity)
  - % of actual frauds caught
  - Missing a fraud = business loss

Precision
  - % of fraud alerts that are actually fraud
  - False alert = customer friction

Confusion Matrix (TN, FP, FN, TP)
  - FN (False Negatives) = frauds we missed - WORST outcome
  - FP (False Positives) = customers falsely flagged - customer friction
  - TP (True Positives) = frauds caught - GOOD
  - TN (True Negatives) = legitimate txns correctly allowed - GOOD

Accuracy - MISLEADING for imbalanced data!
  Example: 99% legitimates, 1% fraud
  Model that predicts "always legitimate" = 99% accuracy but CATCHES ZERO FRAUDS



2. TOP CANDIDATES FOR IMBALANCED FRAUD DETECTION (ROC-AUC > 0.90)
----------------------------------------------------------------------------------------------------------------------------------
                                 Model  Features  ROC-AUC  PR-AUC     F1  Recall  Precision   TP    FP   FN
            XGBoost - Reduced Baseline       342   0.9120  0.5604 0.5262  0.5605     0.4959 2278  2316 1786
           LightGBM - Reduced Baseline       342   0.9118  0.5550 0.5213  0.5672     0.4822 2305  2475 1759
           CatBoost - Reduced Baseline       342   0.9093  0.5119 0.3551  0.7205     0.2356 2928  9500 1136
 XGBoost - Reduced Feature Engineering       348   0.9163  0.5717 0.5536  0.5327     0.5761 2165  1593 1899
LightGBM - Reduced Feature Engineering       348   0.9129  0.5381 0.3958  0.6826     0.2787 2774  7179 1290
CatBoost - Reduced Feature Engineering       348   0.9095  0.5094 0.3409  0.7261     0.2227 2951 10298 1113
                    XGBoost - Baseline       432   0.9114  0.5624 0.5265  0.5706     0.4887 2319  2426 1745
                   LightGBM - Baseline       432   0.9109  0.5498 0.4373  0.6533     0.3286 2655  5424 1409
                   CatBoost - Baseline       432   0.9078  0.5156 0.3420  0.7362     0.2228 2992 10440 1072
         XGBoost - Feature Engineering       439   0.9196  0.5965 0.5813  0.5074     0.6805 2062   968 2002
        LightGBM - Feature Engineering       439   0.9163  0.5593 0.4543  0.6587     0.3467 2677  5045 1387
        CatBoost - Feature Engineering       439   0.9087  0.5065 0.3323  0.7323     0.2149 2976 10871 1088


3. DETAILED COMPARISON - THREE MAIN CANDIDATES
==================================================================================================================================

RF - Baseline
----------------------------------------------------------------------------------------------------------------------------------

Core Metrics (for imbalanced data):
  ROC-AUC:              0.8959  <- Main comparison metric
  PR-AUC:               0.4875  <- Critical for fraud (rare events)
  F1 Score:             0.3733   <- Balance precision & recall

Fraud Detection Performance:
  Recall (catch rate):  0.6097   <- % of frauds actually caught
  Precision:            0.2690  <- % of alerts that are real frauds

Confusion Matrix Breakdown:
  True Negatives (TN):     107309  <- Legitimate txns correctly allowed
  False Positives (FP):      6735  <- Legitimate txns falsely flagged (customer friction)
  False Negatives (FN):      1586  <- Frauds missed (WORST - direct loss!)
  True Positives (TP):       2478  <- Frauds caught (BEST)
  -----------------------------------
  Total samples:           118108

Derived Metrics:
  Specificity:          0.9409   <- % of legitimate txns correctly allowed
  Sensitivity:          0.6097   <- % of frauds caught (same as Recall)
  False Alarm Rate:     0.0591   <- % of legitimate txns falsely flagged
  False Negative Rate:  0.3903   <- % of frauds missed (minimize this!)
  Features:             432 columns

RF - Feature Engineering
----------------------------------------------------------------------------------------------------------------------------------

Core Metrics (for imbalanced data):
  ROC-AUC:              0.8961  <- Main comparison metric
  PR-AUC:               0.4885  <- Critical for fraud (rare events)
  F1 Score:             0.3740   <- Balance precision & recall

Fraud Detection Performance:
  Recall (catch rate):  0.6031   <- % of frauds actually caught
  Precision:            0.2710  <- % of alerts that are real frauds

Confusion Matrix Breakdown:
  True Negatives (TN):     107452  <- Legitimate txns correctly allowed
  False Positives (FP):      6592  <- Legitimate txns falsely flagged (customer friction)
  False Negatives (FN):      1613  <- Frauds missed (WORST - direct loss!)
  True Positives (TP):       2451  <- Frauds caught (BEST)
  -----------------------------------
  Total samples:           118108

Derived Metrics:
  Specificity:          0.9422   <- % of legitimate txns correctly allowed
  Sensitivity:          0.6031   <- % of frauds caught (same as Recall)
  False Alarm Rate:     0.0578   <- % of legitimate txns falsely flagged
  False Negative Rate:  0.3969   <- % of frauds missed (minimize this!)
  Features:             439 columns

RF - Reduced Baseline
----------------------------------------------------------------------------------------------------------------------------------

Core Metrics (for imbalanced data):
  ROC-AUC:              0.8907  <- Main comparison metric
  PR-AUC:               0.4858  <- Critical for fraud (rare events)
  F1 Score:             0.3963   <- Balance precision & recall

Fraud Detection Performance:
  Recall (catch rate):  0.5669   <- % of frauds actually caught
  Precision:            0.3046  <- % of alerts that are real frauds

Confusion Matrix Breakdown:
  True Negatives (TN):     108783  <- Legitimate txns correctly allowed
  False Positives (FP):      5261  <- Legitimate txns falsely flagged (customer friction)
  False Negatives (FN):      1760  <- Frauds missed (WORST - direct loss!)
  True Positives (TP):       2304  <- Frauds caught (BEST)
  -----------------------------------
  Total samples:           118108

Derived Metrics:
  Specificity:          0.9539   <- % of legitimate txns correctly allowed
  Sensitivity:          0.5669   <- % of frauds caught (same as Recall)
  False Alarm Rate:     0.0461   <- % of legitimate txns falsely flagged
  False Negative Rate:  0.4331   <- % of frauds missed (minimize this!)
  Features:             342 columns

RF - Reduced Feature Engineering
----------------------------------------------------------------------------------------------------------------------------------

Core Metrics (for imbalanced data):
  ROC-AUC:              0.8922  <- Main comparison metric
  PR-AUC:               0.4894  <- Critical for fraud (rare events)
  F1 Score:             0.4110   <- Balance precision & recall

Fraud Detection Performance:
  Recall (catch rate):  0.5527   <- % of frauds actually caught
  Precision:            0.3271  <- % of alerts that are real frauds

Confusion Matrix Breakdown:
  True Negatives (TN):     109424  <- Legitimate txns correctly allowed
  False Positives (FP):      4620  <- Legitimate txns falsely flagged (customer friction)
  False Negatives (FN):      1818  <- Frauds missed (WORST - direct loss!)
  True Positives (TP):       2246  <- Frauds caught (BEST)
  -----------------------------------
  Total samples:           118108

Derived Metrics:
  Specificity:          0.9595   <- % of legitimate txns correctly allowed
  Sensitivity:          0.5527   <- % of frauds caught (same as Recall)
  False Alarm Rate:     0.0405   <- % of legitimate txns falsely flagged
  False Negative Rate:  0.4473   <- % of frauds missed (minimize this!)
  Features:             348 columns

LightGBM - Reduced Feature Engineering
----------------------------------------------------------------------------------------------------------------------------------

Core Metrics (for imbalanced data):
  ROC-AUC:              0.9129  <- Main comparison metric
  PR-AUC:               0.5381  <- Critical for fraud (rare events)
  F1 Score:             0.3958   <- Balance precision & recall

Fraud Detection Performance:
  Recall (catch rate):  0.6826   <- % of frauds actually caught
  Precision:            0.2787  <- % of alerts that are real frauds

Confusion Matrix Breakdown:
  True Negatives (TN):     106865  <- Legitimate txns correctly allowed
  False Positives (FP):      7179  <- Legitimate txns falsely flagged (customer friction)
  False Negatives (FN):      1290  <- Frauds missed (WORST - direct loss!)
  True Positives (TP):       2774  <- Frauds caught (BEST)
  -----------------------------------
  Total samples:           118108

Derived Metrics:
  Specificity:          0.9371   <- % of legitimate txns correctly allowed
  Sensitivity:          0.6826   <- % of frauds caught (same as Recall)
  False Alarm Rate:     0.0629   <- % of legitimate txns falsely flagged
  False Negative Rate:  0.3174   <- % of frauds missed (minimize this!)
  Features:             348 columns

XGBoost - Reduced Feature Engineering
----------------------------------------------------------------------------------------------------------------------------------

Core Metrics (for imbalanced data):
  ROC-AUC:              0.9163  <- Main comparison metric
  PR-AUC:               0.5717  <- Critical for fraud (rare events)
  F1 Score:             0.5536   <- Balance precision & recall

Fraud Detection Performance:
  Recall (catch rate):  0.5327   <- % of frauds actually caught
  Precision:            0.5761  <- % of alerts that are real frauds

Confusion Matrix Breakdown:
  True Negatives (TN):     112451  <- Legitimate txns correctly allowed
  False Positives (FP):      1593  <- Legitimate txns falsely flagged (customer friction)
  False Negatives (FN):      1899  <- Frauds missed (WORST - direct loss!)
  True Positives (TP):       2165  <- Frauds caught (BEST)
  -----------------------------------
  Total samples:           118108

Derived Metrics:
  Specificity:          0.9860   <- % of legitimate txns correctly allowed
  Sensitivity:          0.5327   <- % of frauds caught (same as Recall)
  False Alarm Rate:     0.0140   <- % of legitimate txns falsely flagged
  False Negative Rate:  0.4673   <- % of frauds missed (minimize this!)
  Features:             348 columns

CatBoost - Reduced Feature Engineering
----------------------------------------------------------------------------------------------------------------------------------

Core Metrics (for imbalanced data):
  ROC-AUC:              0.9095  <- Main comparison metric
  PR-AUC:               0.5094  <- Critical for fraud (rare events)
  F1 Score:             0.3409   <- Balance precision & recall

Fraud Detection Performance:
  Recall (catch rate):  0.7261   <- % of frauds actually caught
  Precision:            0.2227  <- % of alerts that are real frauds

Confusion Matrix Breakdown:
  True Negatives (TN):     103746  <- Legitimate txns correctly allowed
  False Positives (FP):     10298  <- Legitimate txns falsely flagged (customer friction)
  False Negatives (FN):      1113  <- Frauds missed (WORST - direct loss!)
  True Positives (TP):       2951  <- Frauds caught (BEST)
  -----------------------------------
  Total samples:           118108

Derived Metrics:
  Specificity:          0.9097   <- % of legitimate txns correctly allowed
  Sensitivity:          0.7261   <- % of frauds caught (same as Recall)
  False Alarm Rate:     0.0903   <- % of legitimate txns falsely flagged
  False Negative Rate:  0.2739   <- % of frauds missed (minimize this!)
  Features:             348 columns


4. RECOMMENDATION FOR IMBALANCED FRAUD DETECTION
==================================================================================================================================

KEY INSIGHT FOR IMBALANCED DATA:

Priority:
1. MINIMIZE FN (False Negatives / Missed Frauds) <- Direct business loss
2. MAINTAIN ROC-AUC > 0.90 <- Threshold-independent quality
3. MAXIMIZE F1 & Recall <- Better fraud detection
4. MANAGE FP (False Positives) <- Customer experience
5. IGNORE Accuracy <- Misleading for imbalanced data

BEST CHOICE: re-run 02_ml_models_fit.ipynb, then pick the row with highest PR-AUC / F1 among the four tables.

Compare Baseline vs Feature Engineering vs Reduced Baseline vs Reduced Feature Engineering
for each model family. Group-ablation permutations (Remove C / D / M / id / V) are no longer trained.

==================================================================================================================================

## Feature-count trade-off

Best model at each width, and the smallest feature set that still clears ROC-AUC 0.90.

In [6]:
print("=" * 100)
print("ANALYZING ALL CONFIGURATIONS: Looking for Best Trade-offs")
print("=" * 100)

print("\n1. BY FEATURE COUNT (Least Parameters)")
print("-" * 100)

for feature_count in sorted(all_results["Features"].unique()):
    group = all_results[all_results["Features"] == feature_count].sort_values(
        "ROC-AUC", ascending=False
    )
    if len(group) > 0:
        best = group.iloc[0]
        print(
            f"\nFeatures: {int(feature_count):3d} | Best: {best['Model'][:40]:40s} | "
            f"ROC-AUC: {best['ROC-AUC']:.4f} | F1: {best['F1']:.4f}"
        )

print("\n\n2. TRADE-OFF ANALYSIS (Best Metrics vs Fewest Features)")
print("-" * 100)

sorted_by_features = all_results.sort_values(["Features", "ROC-AUC"], ascending=[True, False])

print("\nTop performer in each feature-reduction tier:")
seen_features = set()
count = 0
for _, row in sorted_by_features.iterrows():
    if row["Features"] not in seen_features and count < 8:
        seen_features.add(row["Features"])
        print(
            f"  {int(row['Features']):3d} features | {row['Model'][:45]:45s} | "
            f"ROC-AUC: {row['ROC-AUC']:.4f} | F1: {row['F1']:.4f} | Type: {row['ModelType']}"
        )
        count += 1

print("\n\n3. PER MODEL FAMILY (fewest features first)")
print("-" * 100)
for family in MODEL_ORDER:
    frame = all_results[all_results["ModelType"] == family]
    if frame.empty:
        continue
    print(f"\n{family}")
    display(
        frame.nsmallest(10, "Features")[
            [c for c in ["Model", "Features", "ROC-AUC", "PR-AUC", "F1", "Accuracy"] if c in frame.columns]
        ]
    )

print("\n\n4. BEST BY DIFFERENT METRICS")
print("-" * 100)

few = all_results[all_results["Features"] < 100]
if few.empty:
    print("No runs with <100 features (group ablations were removed). Ranking the four tables instead.")
    few = all_results
best_roc_few = few.nlargest(1, "ROC-AUC").iloc[0]
print("\nBest ROC-AUC:")
print(
    f"  {best_roc_few['Model']} | Features: {best_roc_few['Features']:.0f} | "
    f"ROC-AUC: {best_roc_few['ROC-AUC']:.4f} | F1: {best_roc_few['F1']:.4f}"
)
best_f1_few = few.nlargest(1, "F1").iloc[0]
print("\nBest F1:")
print(
    f"  {best_f1_few['Model']} | Features: {best_f1_few['Features']:.0f} | "
    f"ROC-AUC: {best_f1_few['ROC-AUC']:.4f} | F1: {best_f1_few['F1']:.4f}"
)

ranked = all_results.copy()
ranked["Balance"] = (ranked["ROC-AUC"] + ranked["F1"]) / 2
best_balanced_few = ranked.nlargest(1, "Balance").iloc[0]
print("\nBest Balance (ROC-AUC + F1 avg):")
print(
    f"  {best_balanced_few['Model']} | Features: {best_balanced_few['Features']:.0f} | "
    f"ROC-AUC: {best_balanced_few['ROC-AUC']:.4f} | F1: {best_balanced_few['F1']:.4f}"
)

qualifying = all_results[all_results["ROC-AUC"] > 0.90]
if len(qualifying) > 0:
    best_minimal = qualifying.nsmallest(1, "Features").iloc[0]
    print("\nMinimum features with ROC-AUC >0.90:")
    print(
        f"  {best_minimal['Model']} | Features: {best_minimal['Features']:.0f} | "
        f"ROC-AUC: {best_minimal['ROC-AUC']:.4f} | F1: {best_minimal['F1']:.4f}"
    )

print("\n\n" + "=" * 100)

====================================================================================================
ANALYZING ALL CONFIGURATIONS: Looking for Best Trade-offs
====================================================================================================

1. BY FEATURE COUNT (Least Parameters)
----------------------------------------------------------------------------------------------------

Features: 342 | Best: XGBoost - Reduced Baseline               | ROC-AUC: 0.9120 | F1: 0.5262

Features: 348 | Best: XGBoost - Reduced Feature Engineering    | ROC-AUC: 0.9163 | F1: 0.5536

Features: 432 | Best: XGBoost - Baseline                       | ROC-AUC: 0.9114 | F1: 0.5265

Features: 439 | Best: XGBoost - Feature Engineering            | ROC-AUC: 0.9196 | F1: 0.5813


2. TRADE-OFF ANALYSIS (Best Metrics vs Fewest Features)
----------------------------------------------------------------------------------------------------

Top performer in each feature-reduction tier:
  342 features | XGBoost - Reduced Baseline                    | ROC-AUC: 0.9120 | F1: 0.5262 | Type: XGBoost
  348 features | XGBoost - Reduced Feature Engineering         | ROC-AUC: 0.9163 | F1: 0.5536 | Type: XGBoost
  432 features | XGBoost - Baseline                            | ROC-AUC: 0.9114 | F1: 0.5265 | Type: XGBoost
  439 features | XGBoost - Feature Engineering                 | ROC-AUC: 0.9196 | F1: 0.5813 | Type: XGBoost


3. PER MODEL FAMILY (fewest features first)
----------------------------------------------------------------------------------------------------

LogisticRegression

,Model,Features,ROC-AUC,PR-AUC,F1,Accuracy
2,Logistic Regression - Reduced Baseline,342,0.8248,0.1771,0.1513,0.6881
3,Logistic Regression - Reduced Feature Engineering,348,0.8248,0.1802,0.1536,0.6976
0,Logistic Regression - Baseline,432,0.8335,0.2067,0.1583,0.7058
1,Logistic Regression - Feature Engineering,439,0.8334,0.2094,0.1595,0.7091

DecisionTree

,Model,Features,ROC-AUC,PR-AUC,F1,Accuracy
6,Decision Tree - Reduced Baseline,342,0.8221,0.3320,0.2044,0.8237
7,Decision Tree - Reduced Feature Engineering,348,0.8307,0.3506,0.2193,0.8306
4,Decision Tree - Baseline,432,0.8251,0.3310,0.1986,0.8150
5,Decision Tree - Feature Engineering,439,0.7965,0.3368,0.2035,0.8181

RandomForest

,Model,Features,ROC-AUC,PR-AUC,F1,Accuracy
10,RF - Reduced Baseline,342,0.8907,0.4858,0.3963,0.9406
11,RF - Reduced Feature Engineering,348,0.8922,0.4894,0.4110,0.9455
8,RF - Baseline,432,0.8959,0.4875,0.3733,0.9295
9,RF - Feature Engineering,439,0.8961,0.4885,0.3740,0.9305

LightGBM

,Model,Features,ROC-AUC,PR-AUC,F1,Accuracy
14,LightGBM - Reduced Baseline,342,0.9118,0.5550,0.5213,0.9642
15,LightGBM - Reduced Feature Engineering,348,0.9129,0.5381,0.3958,0.9283
12,LightGBM - Baseline,432,0.9109,0.5498,0.4373,0.9421
13,LightGBM - Feature Engineering,439,0.9163,0.5593,0.4543,0.9455

XGBoost

,Model,Features,ROC-AUC,PR-AUC,F1,Accuracy
18,XGBoost - Reduced Baseline,342,0.9120,0.5604,0.5262,0.9653
19,XGBoost - Reduced Feature Engineering,348,0.9163,0.5717,0.5536,0.9704
16,XGBoost - Baseline,432,0.9114,0.5624,0.5265,0.9647
17,XGBoost - Feature Engineering,439,0.9196,0.5965,0.5813,0.9749

CatBoost

,Model,Features,ROC-AUC,PR-AUC,F1,Accuracy
22,CatBoost - Reduced Baseline,342,0.9093,0.5119,0.3551,0.9099
23,CatBoost - Reduced Feature Engineering,348,0.9095,0.5094,0.3409,0.9034
20,CatBoost - Baseline,432,0.9078,0.5156,0.3420,0.9025
21,CatBoost - Feature Engineering,439,0.9087,0.5065,0.3323,0.8987

4. BEST BY DIFFERENT METRICS
----------------------------------------------------------------------------------------------------
No runs with <100 features (group ablations were removed). Ranking the four tables instead.

Best ROC-AUC:
  XGBoost - Feature Engineering | Features: 439 | ROC-AUC: 0.9196 | F1: 0.5813

Best F1:
  XGBoost - Feature Engineering | Features: 439 | ROC-AUC: 0.9196 | F1: 0.5813

Best Balance (ROC-AUC + F1 avg):
  XGBoost - Feature Engineering | Features: 439 | ROC-AUC: 0.9196 | F1: 0.5813

Minimum features with ROC-AUC >0.90:
  LightGBM - Reduced Baseline | Features: 342 | ROC-AUC: 0.9118 | F1: 0.5213


====================================================================================================

## Test submissions

Refit every Optuna run on the full train table for that feature set, then score `dataset/merged_test.parquet`. No GridSearchCV — params come from `BestParams` in `ml_results.parquet`.

In [7]:
RANDOM_SEED = 42
ID_COLS = ["isFraud", "TransactionID"]
FE_COLS = ["uid", "uid2", "DT_month", "DT_week", "DT_day", "DT_weekday", "DT_hour"]


def _scale_pos_weight(y):
    n_neg = int((y == 0).sum())
    n_pos = max(int((y == 1).sum()), 1)
    return n_neg / n_pos


def build_model(model_type, params, y_train, n_jobs=-1):
    p = dict(params)
    if model_type == "LogisticRegression":
        return Pipeline(
            [
                ("scaler", StandardScaler()),
                (
                    "clf",
                    LogisticRegression(
                        class_weight="balanced",
                        max_iter=2000,
                        solver="lbfgs",
                        random_state=RANDOM_SEED,
                        **p,
                    ),
                ),
            ]
        )
    if model_type == "DecisionTree":
        return DecisionTreeClassifier(
            class_weight="balanced", random_state=RANDOM_SEED, **p
        )
    if model_type == "RandomForest":
        return RandomForestClassifier(
            class_weight="balanced", random_state=RANDOM_SEED, n_jobs=n_jobs, **p
        )
    if model_type == "LightGBM":
        return LGBMClassifier(
            class_weight="balanced",
            random_state=RANDOM_SEED,
            n_jobs=n_jobs,
            verbosity=-1,
            subsample_freq=1,
            **p,
        )
    if model_type == "XGBoost":
        return XGBClassifier(
            random_state=RANDOM_SEED,
            n_jobs=n_jobs,
            eval_metric="logloss",
            tree_method="hist",
            scale_pos_weight=_scale_pos_weight(y_train),
            **p,
        )
    if model_type == "CatBoost":
        return CatBoostClassifier(
            random_seed=RANDOM_SEED,
            auto_class_weights="Balanced",
            verbose=False,
            allow_writing_files=False,
            thread_count=n_jobs if n_jobs > 0 else -1,
            **p,
        )
    raise ValueError(f"Unknown model_type {model_type}")


def parse_params(value):
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return {}
    if isinstance(value, dict):
        return dict(value)
    return json.loads(value)


def feature_columns(table, dataset):
    if dataset in ("Baseline", "Reduced Baseline"):
        return [c for c in table.columns if c not in ID_COLS + FE_COLS]
    return [c for c in table.columns if c not in ID_COLS]


def submission_name(model_type, dataset):
    return f"{model_type}_{dataset.replace(' ', '_')}_submission.csv"


def fraud_score(model, X):
    if hasattr(model, "predict_proba"):
        return model.predict_proba(X)[:, 1]
    return model.decision_function(X)


runs = all_results.copy()
runs = runs[~runs["Model"].astype(str).str.startswith(("SVM -", "KNN -"))]
if "BestParams" not in runs.columns or runs["BestParams"].isna().any():
    raise ValueError("BestParams missing — re-run Optuna cells in 02_ml_models_fit.ipynb")

print("Loading train / reduced / test …")
train_full = (
    pd.read_parquet(DATASET_PATH / "merged_train.parquet")
    .sort_values("TransactionDT")
    .reset_index(drop=True)
)
train_reduced = (
    pd.read_parquet(DATASET_PATH / "merged_train_reduced.parquet")
    .sort_values("TransactionDT")
    .reset_index(drop=True)
)
test = pd.read_parquet(DATASET_PATH / "merged_test.parquet")
test_ids = test["TransactionID"].to_numpy()
print(f"train {train_full.shape}  reduced {train_reduced.shape}  test {test.shape}")

written = []
for _, row in runs.sort_values(["ModelType", "Dataset"]).iterrows():
    model_type = str(row["ModelType"])
    dataset = str(row["Dataset"])
    out_path = RESULTS_DIR / submission_name(model_type, dataset)
    if out_path.exists():
        print(f"skip {out_path.name}")
        written.append(out_path.name)
        continue

    table = train_reduced if dataset.startswith("Reduced") else train_full
    cols = feature_columns(table, dataset)
    missing_cols = [c for c in cols if c not in test.columns]
    if missing_cols:
        raise ValueError(f"{row['Model']}: test missing {missing_cols[:8]}")

    params = parse_params(row["BestParams"])
    X_train = table[cols]
    y_train = table["isFraud"]
    X_test = test[cols]
    print(f"fit {row['Model']}  features={len(cols)}")
    model = build_model(model_type, params, y_train, n_jobs=-1)
    model.fit(X_train, y_train)
    scores = fraud_score(model, X_test)
    submission = pd.DataFrame(
        {"TransactionID": test_ids, "IsFraud": np.asarray(scores, dtype=np.float64)}
    )
    submission.to_csv(out_path, index=False)
    print(f"wrote {out_path.name}  rows={len(submission):,}")
    written.append(out_path.name)
    del model, X_train, X_test, scores, submission
    gc.collect()

print(f"\\n{len(written)} files in {RESULTS_DIR}")
for name in written:
    print(f"  {name}")

Loading train / reduced / test …
train (590540, 441)  reduced (590540, 350)  test (506691, 440)
skip CatBoost_Baseline_submission.csv
skip CatBoost_Feature_Engineering_submission.csv
skip CatBoost_Reduced_Baseline_submission.csv
skip CatBoost_Reduced_Feature_Engineering_submission.csv
skip DecisionTree_Baseline_submission.csv
skip DecisionTree_Feature_Engineering_submission.csv
skip DecisionTree_Reduced_Baseline_submission.csv
skip DecisionTree_Reduced_Feature_Engineering_submission.csv
skip LightGBM_Baseline_submission.csv
skip LightGBM_Feature_Engineering_submission.csv
skip LightGBM_Reduced_Baseline_submission.csv
skip LightGBM_Reduced_Feature_Engineering_submission.csv
skip LogisticRegression_Baseline_submission.csv
skip LogisticRegression_Feature_Engineering_submission.csv
skip LogisticRegression_Reduced_Baseline_submission.csv
skip LogisticRegression_Reduced_Feature_Engineering_submission.csv
skip RandomForest_Baseline_submission.csv
skip RandomForest_Feature_Engineering_submission.csv
skip RandomForest_Reduced_Baseline_submission.csv
skip RandomForest_Reduced_Feature_Engineering_submission.csv
skip XGBoost_Baseline_submission.csv
skip XGBoost_Feature_Engineering_submission.csv
skip XGBoost_Reduced_Baseline_submission.csv
skip XGBoost_Reduced_Feature_Engineering_submission.csv
\n24 files in d:\source\RMIT\master-of-ai-new\2026-semester-02\minor-thesis\results
  CatBoost_Baseline_submission.csv
  CatBoost_Feature_Engineering_submission.csv
  CatBoost_Reduced_Baseline_submission.csv
  CatBoost_Reduced_Feature_Engineering_submission.csv
  DecisionTree_Baseline_submission.csv
  DecisionTree_Feature_Engineering_submission.csv
  DecisionTree_Reduced_Baseline_submission.csv
  DecisionTree_Reduced_Feature_Engineering_submission.csv
  LightGBM_Baseline_submission.csv
  LightGBM_Feature_Engineering_submission.csv
  LightGBM_Reduced_Baseline_submission.csv
  LightGBM_Reduced_Feature_Engineering_submission.csv
  LogisticRegression_Baseline_submission.csv
  LogisticRegression_Feature_Engineering_submission.csv
  LogisticRegression_Reduced_Baseline_submission.csv
  LogisticRegression_Reduced_Feature_Engineering_submission.csv
  RandomForest_Baseline_submission.csv
  RandomForest_Feature_Engineering_submission.csv
  RandomForest_Reduced_Baseline_submission.csv
  RandomForest_Reduced_Feature_Engineering_submission.csv
  XGBoost_Baseline_submission.csv
  XGBoost_Feature_Engineering_submission.csv
  XGBoost_Reduced_Baseline_submission.csv
  XGBoost_Reduced_Feature_Engineering_submission.csv

## Summary

This notebook ranks the **six models × four feature tables** written by `02_ml_models_fit.ipynb`, then writes test submissions from those Optuna params to `results/`.